"""
Agents: read the English part only. 中文仅供人类阅读。

Strategy callbacks stub for "{strategy_name}" — generated by sf_formal.py gen-stub at {generated_at}.

This file is the contract between the strategy-formalizer output and the
downstream trading agent. Every abstract method below is one decision the
strategy delegates to the downstream agent (a role=callback term). The
method docstring carries the agreed definition, the point in the execution
steps where it is invoked, its inputs and output, and every auxiliary,
constraint and parameter term that qualifies it. Implement a subclass; do not
edit this file by hand, regenerate it from S7_formal.json instead. Market
data, instrument lists and factor helpers are the downstream agent's own
concern and are not provided here.

本文件是 strategy-formalizer 的产出与下游交易 agent 之间的契约。下面每个抽象方法对应策略
交给下游 agent 判断的一个决策（role=callback 的术语）。方法 docstring 包含商定的定义、在
执行步骤中的调用位置、输入输出，以及限定它的全部辅助/约束/参数术语。请实现子类，不要手工
修改本文件，需要变更时从 S7_formal.json 重新生成。行情数据、品种列表、因子计算由下游
agent 自行提供，这里不涉及。
"""
