"""
Agents: read the English part only. 中文仅供人类阅读。

Strategy callbacks stub for "{strategy_name}" — generated by sf_formal.py gen-stub at {generated_at}.

This file is the contract between the strategy-formalizer output and the
downstream trading agent. Every abstract method of StrategyCallbacks is one
decision the strategy delegates to the downstream agent (a role=callback
term). The method docstring carries the agreed definition, the point in the
execution steps where it is invoked, its inputs and output, and every
auxiliary, constraint and parameter term that qualifies it. The dataclasses
above the class are the standard interface types every stub shares: bars,
market data, instrument, position, and the two compound results. Implement a
subclass and fill the dataclasses from your own data layer; do not edit this
file by hand, regenerate it from S7_formal.json instead. Market data,
instrument lists and factor helpers are the downstream agent's own concern.

本文件是 strategy-formalizer 的产出与下游交易 agent 之间的契约。StrategyCallbacks 的每个
抽象方法对应策略交给下游 agent 判断的一个决策（role=callback 的术语）。方法 docstring 包含
商定的定义、在执行步骤中的调用位置、输入输出，以及限定它的全部辅助/约束/参数术语。类之前的
dataclass 是所有桩代码共用的标准接口类型：K 线、行情数据、品种、持仓，以及两个复合结果。
请实现子类，并用你自己的数据层填充这些 dataclass；不要手工修改本文件，需要变更时从
S7_formal.json 重新生成。行情数据、品种列表、因子计算由下游 agent 自行提供。
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal, Optional

Direction = Literal["long", "short"]
"""Position / signal direction. 持仓或信号方向。"""


@dataclass
class Bar:
    """
    One OHLCV bar of any timeframe. The downstream agent fills it from its
    own data source; `extra` carries indicator values or anything else.

    任意周期的一根 OHLCV K 线。由下游 agent 从自己的数据源填充；`extra` 放指标值等附加信息。
    """
    time: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    open_interest: Optional[float] = None
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class MarketData:
    """
    Bars of one instrument on one timeframe, newest last, plus the timeframe
    label (e.g. "1d", "30m") and free-form context such as precomputed
    indicators or support/resistance levels.

    某品种在某一周期上的 K 线序列（最新在最后），加上周期标签（如 "1d"、"30m"）和自由格式的
    上下文（预计算指标、支撑阻力位等）。
    """
    instrument: str
    timeframe: str
    bars: list[Bar]
    context: dict[str, Any] = field(default_factory=dict)


@dataclass
class Instrument:
    """
    What is being traded: symbol, contract (if any), tick size, multiplier.

    交易对象：代码、合约（若有）、最小变动价位、合约乘数。
    """
    symbol: str
    contract: Optional[str] = None
    tick_size: float = 1.0
    multiplier: float = 1.0
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class Position:
    """
    An open position as the callbacks see it.

    回调所看到的当前持仓。
    """
    instrument: Instrument
    direction: Direction
    entry_price: float
    entry_time: datetime
    size: float
    stop_price: Optional[float] = None
    stop_at_cost: bool = False
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class EntryDecision:
    """
    Result of an entry-signal callback: whether to enter and, if so, at what
    limit price.

    入场信号回调的结果：是否入场，入场时的限价。
    """
    decision: Literal["enter", "no_enter"]
    entry_price: Optional[float] = None
    note: str = ""


@dataclass
class StopDistance:
    """
    Result of a stop-placement callback: a distance from the entry price,
    declared as points or percent.

    止损设置回调的结果：相对入场价的距离，须声明是点数还是百分比。
    """
    value: float
    unit: Literal["points", "percent"]
