"""
Agents: read the English part only. 中文仅供人类阅读。

Strategy driver for "{strategy_name}" — generated by sf_driver.py gen at {generated_at}.
Do not edit by hand; edit the `flow` section of S7_formal.json and regenerate.

This module turns the strategy's execution steps into code. `StrategyDriver.on_event(event, ctx)`
is a generated, event-driven state machine. The downstream agent calls it whenever one
of the scheduling events happens: `tick` (a new price), `minor_bar` (a minor-timeframe
bar closed), `major_bar` (a major-timeframe bar closed) or `timer`. Each flow rule
declares the event it runs on; on other events the rule is skipped and the value its
callback produced last time is read from `SignalCache`. This is how pre-entry judgements
(polled on bar closes) and in-position judgements (slow, major-timeframe) coexist with
tick-level stop checks without the driver ever blocking. Callbacks declared `async` in
their schedule must return immediately; returning None keeps the previous cached value,
so the downstream agent may compute them in a thread or coroutine and hand the result
back through the callback. The driver never places orders: the downstream agent
implements `ExecutionPort`, executes each action and keeps `Position` up to date for
the next call. Built in rather than delegated: the stop-hit test (exit path one, on
every tick) and sizing a new position from the account's per-trade risk fraction.
`RecordingPort` is an in-memory reference port used by the dry-run and by tests.
`step(ctx)` is shorthand for `on_event("tick", ctx)`.

本模块把策略的执行步骤变成代码。`StrategyDriver.on_event(event, ctx)` 是生成的事件驱动状态机。
下游 agent 在调度事件发生时调用它：`tick`（新价格）、`minor_bar`（小周期 K 线收盘）、`major_bar`
（大周期 K 线收盘）或 `timer`。每条 flow 规则声明自己在哪个事件上执行；其他事件上该规则被跳过，
其回调上一次的结果从 `SignalCache` 读取。入场前的判断（按 K 线收盘轮询）、持仓期的慢判断（大周期）
与 tick 级止损检查因此可以共存，driver 永不阻塞。schedule 声明为 `async` 的回调必须立即返回；
返回 None 表示沿用上次缓存值，下游可以在线程或协程里计算，再通过回调把结果交回。driver 不下单：
下游实现 `ExecutionPort`，执行每个动作并为下一次调用维护 `Position`。内置而非委托的两件事：止损
触发判断（出场路径一，每个 tick）和按账户单笔风险比例反算仓位。`RecordingPort` 是 dry-run 与测试
用的内存版参考实现。`step(ctx)` 等价于 `on_event("tick", ctx)`。
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal, Optional, Protocol

{stub_import}

ActionKind = Literal["enter", "close", "set_stop"]
Event = Literal["tick", "minor_bar", "major_bar", "timer"]
EVENTS: tuple[str, ...] = ("tick", "minor_bar", "major_bar", "timer")


@dataclass
class CachedSignal:
    """
    One callback result kept by SignalCache with the event and sequence
    number at which it was produced.

    SignalCache 保存的一个回调结果，附带产生它的事件及序号。
    """
    value: Any
    event: str
    seq: int


class SignalCache:
    """
    Latest result of every callback, keyed by callback name. Rules read from
    it on events that are not their trigger, and async callbacks that return
    None leave the cached value in place. `seq` counts events so staleness
    can be measured.

    每个回调的最新结果，按回调名索引。规则在非触发事件上从这里读值；返回 None 的异步回调
    保留缓存值。`seq` 对事件计数，便于衡量陈旧程度。
    """

    def __init__(self) -> None:
        """
        Start empty.

        初始为空。
        """
        self._items: dict[str, CachedSignal] = {}
        self.seq = 0

    def get(self, name: str) -> Any:
        """
        Cached value for a callback, or None when it has never been produced.

        某回调的缓存值；从未产生过则为 None。
        """
        item = self._items.get(name)
        return None if item is None else item.value

    def put(self, name: str, value: Any, event: str) -> None:
        """
        Store a fresh result.

        存入新结果。
        """
        self._items[name] = CachedSignal(value=value, event=event, seq=self.seq)

    def invalidate(self, name: str) -> None:
        """
        Forget a result (used after an entry so a stale entry signal cannot
        re-fire).

        清除某结果（入场后用，避免陈旧的入场信号再次触发）。
        """
        self._items.pop(name, None)

    def age(self, name: str) -> Optional[int]:
        """
        Number of events since the result was produced, or None.

        该结果产生以来经过的事件数；没有则为 None。
        """
        item = self._items.get(name)
        return None if item is None else self.seq - item.seq


@dataclass
class Action:
    """
    One instruction from the driver to the execution port. `kind` is enter /
    close / set_stop; `reason` distinguishes `set_stop` at cost ("cost") from a
    trailing move ("trail") and names the exit path for `close` ("stop",
    "reversal", ...). `rule_id` is the flow rule that produced it.

    driver 发给下单端的一条指令。`kind` 为 enter / close / set_stop；`reason` 区分移损至成本
    （"cost"）与移动止损（"trail"），并给出平仓原因（"stop"、"reversal"…）。`rule_id` 是产生
    它的 flow 规则。
    """
    kind: ActionKind
    rule_id: str
    direction: Optional[Direction] = None
    price: Optional[float] = None
    size: Optional[float] = None
    stop_price: Optional[float] = None
    reason: str = ""

    def label(self) -> str:
        """
        Short label used in traces and dry-run expectations: enter,
        move_stop_to_cost, move_stop, set_stop, close:<reason>.

        用于轨迹和 dry-run 期望值的短标签：enter、move_stop_to_cost、move_stop、set_stop、
        close:<原因>。
        """
        if self.kind == "enter":
            return "enter"
        if self.kind == "close":
            return f"close:{self.reason}" if self.reason else "close"
        return {"cost": "move_stop_to_cost", "trail": "move_stop"}.get(self.reason, "set_stop")


@dataclass
class StepContext:
    """
    Everything one evaluation of the driver may look at. The downstream agent
    builds it from its own data layer before each `step()` call.

    driver 一次评估可以看到的全部信息，由下游 agent 在每次 `step()` 前从自己的数据层构造。
    """
    instrument: Instrument
    major_tf_data: MarketData
    minor_tf_data: MarketData
    position: Optional[Position] = None
    major_tf_context: Optional[MarketData] = None
    last_price: Optional[float] = None
    now: Optional[datetime] = None
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class Account:
    """
    Account-level inputs for sizing: capital and the per-trade loss fraction
    (parameter per_trade_loss_ratio). `size_from_risk` implements the "light
    position" constraint: contracts = floor(capital * ratio / (stop distance in
    price × multiplier)).

    用于仓位计算的账户信息：本金和单笔亏损占比（参数 per_trade_loss_ratio）。`size_from_risk`
    实现"轻仓"约束：手数 = floor(本金 × 比例 / (止损价差 × 合约乘数))。
    """
    capital: float
    per_trade_loss_ratio: float
    min_size: float = 1.0

    def size_from_risk(self, entry_price: float, stop: "StopDistance | float", instrument: Instrument) -> float:
        """
        Position size for a new entry given the stop distance. Returns 0 when
        the risk budget cannot afford one contract.

        根据止损距离计算新仓手数；风险预算不足一手时返回 0。
        """
        distance = stop_distance_in_price(entry_price, stop)
        if distance <= 0:
            return 0.0
        per_unit = distance * max(instrument.multiplier, 1e-12)
        size = math.floor(self.capital * self.per_trade_loss_ratio / per_unit)
        return float(size) if size >= self.min_size else 0.0


def stop_distance_in_price(entry_price: float, stop: "StopDistance | float") -> float:
    """
    Convert a StopDistance (points or percent) or a bare number of points into
    a price distance.

    把 StopDistance（点数或百分比）或裸点数转换成价格距离。
    """
    if isinstance(stop, (int, float)):
        return float(stop)
    return float(stop.value) if stop.unit == "points" else float(entry_price) * float(stop.value) / 100.0


def stop_price_from(entry_price: float, direction: Direction, stop: "StopDistance | float") -> float:
    """
    Initial stop price: below entry for a long, above for a short.

    初始止损价：多头在入场价之下，空头在入场价之上。
    """
    d = stop_distance_in_price(entry_price, stop)
    return entry_price - d if direction == "long" else entry_price + d


class ExecutionPort(Protocol):
    """
    What the downstream agent implements to execute actions. `enter` must
    return the resulting Position (with stop_price set); `set_stop` must update
    position.stop_price and set position.stop_at_cost when action.reason ==
    "cost"; `close` must flatten.

    下游 agent 实现的下单接口。`enter` 必须返回建立的 Position（含 stop_price）；`set_stop`
    必须更新 position.stop_price，且在 action.reason == "cost" 时置 stop_at_cost；`close` 必须
    平仓。
    """

    def enter(self, action: Action, ctx: StepContext) -> Position: ...
    def close(self, action: Action, ctx: StepContext) -> None: ...
    def set_stop(self, action: Action, ctx: StepContext) -> None: ...


class RecordingPort:
    """
    In-memory reference ExecutionPort: fills at the action price, keeps one
    Position, records every action. Used by the dry-run and by tests.

    内存版参考下单端：按动作价格成交、维护一个 Position、记录每个动作。供 dry-run 与测试使用。
    """

    def __init__(self) -> None:
        """
        Start flat with an empty action log.

        初始为空仓、空日志。
        """
        self.position: Optional[Position] = None
        self.log: list[Action] = []

    def apply(self, action: Action, ctx: StepContext) -> None:
        """
        Dispatch one action to enter / set_stop / close.

        把一个动作分发到 enter / set_stop / close。
        """
        self.log.append(action)
        {"enter": self.enter, "close": self.close, "set_stop": self.set_stop}[action.kind](action, ctx)

    def enter(self, action: Action, ctx: StepContext) -> Position:
        """
        Open a position at the action price with the given stop.

        按动作价格开仓并设置止损。
        """
        self.position = Position(
            instrument=ctx.instrument, direction=action.direction, entry_price=float(action.price),
            entry_time=ctx.now or datetime.now(), size=float(action.size or 0), stop_price=action.stop_price,
            stop_at_cost=False,
        )
        return self.position

    def close(self, action: Action, ctx: StepContext) -> None:
        """
        Flatten.

        平仓。
        """
        self.position = None

    def set_stop(self, action: Action, ctx: StepContext) -> None:
        """
        Move the stop; a "cost" move marks stop_at_cost.

        移动止损；原因为 "cost" 时标记 stop_at_cost。
        """
        if self.position is not None:
            self.position.stop_price = action.stop_price
            if action.reason == "cost":
                self.position.stop_at_cost = True


class StrategyDriverBase:
    """
    Runtime shared by every generated driver: state, built-in stop-hit test and
    the action constructors used by the generated `step()`.

    所有生成的 driver 共用的运行时：状态、内置的止损触发判断，以及生成的 `step()` 使用的动作
    构造器。
    """

    initial_state: str = "{initial_state}"
    # name -> (trigger event, mode, output type); filled by the generated subclass
    # 回调名 -> (触发事件, 模式, 输出类型)；由生成的子类填充
    callback_meta: dict[str, tuple[str, str, str]] = {}

    def __init__(self, callbacks: StrategyCallbacks, account: Account) -> None:
        """
        Bind the callbacks implementation and the account; start in the
        initial state with an empty signal cache.

        绑定回调实现与账户，置为初始状态，信号缓存为空。
        """
        self.callbacks = callbacks
        self.account = account
        self.state = self.initial_state
        self.cache = SignalCache()

    def step(self, ctx: StepContext) -> list[Action]:
        """
        Shorthand for a tick event.

        等价于一次 tick 事件。
        """
        return self.on_event("tick", ctx)

    def on_event(self, event: Event, ctx: StepContext) -> list[Action]:
        """
        Generated in the subclass: evaluate the flow for one event.

        由子类生成：对一个事件评估一遍 flow。
        """
        raise NotImplementedError

    def _call(self, name: str, event: str, **kwargs: Any) -> Any:
        """
        Invoke a callback on its trigger event and cache the result. For a
        callback scheduled `async`, a None result means "no fresh value yet"
        and the previous cached value is returned instead.

        在触发事件上调用回调并缓存结果。schedule 为 `async` 的回调返回 None 表示"尚无新值"，
        此时返回之前的缓存值。
        """
        result = getattr(self.callbacks, name)(**kwargs)
        mode = self.callback_meta.get(name, ("", "sync", ""))[1]
        if result is None and mode == "async":
            return self.cache.get(name)
        self.cache.put(name, result, event)
        return result

    def stop_hit(self, ctx: StepContext) -> bool:
        """
        Exit path one: the last price has reached the position's stop (long:
        at or below; short: at or above).

        出场路径一：最新价触及持仓止损（多头：不高于止损价；空头：不低于止损价）。
        """
        p = ctx.position
        if p is None or p.stop_price is None or ctx.last_price is None:
            return False
        return ctx.last_price <= p.stop_price if p.direction == "long" else ctx.last_price >= p.stop_price

    def _enter(self, rule_id: str, direction: Direction, entry_price: float, stop: "StopDistance | float",
               ctx: StepContext) -> Action:
        """
        Build the enter action: size from account risk, initial stop from the
        stop distance.

        构造开仓动作：按账户风险反算手数，按止损距离算初始止损价。
        """
        size = self.account.size_from_risk(entry_price, stop, ctx.instrument)
        for name, (_, _, otype) in self.callback_meta.items():
            if otype == "EntryDecision":
                self.cache.invalidate(name)  # a consumed entry signal must not re-fire from cache / 已用的入场信号不得再触发
        return Action(kind="enter", rule_id=rule_id, direction=direction, price=float(entry_price), size=size,
                      stop_price=stop_price_from(entry_price, direction, stop))

    def _move_stop_to_cost(self, rule_id: str, ctx: StepContext) -> Action:
        """
        Build the set_stop action that moves the stop to the entry price.

        构造把止损移到入场价的动作。
        """
        return Action(kind="set_stop", rule_id=rule_id, stop_price=float(ctx.position.entry_price), reason="cost")

    def _move_stop(self, rule_id: str, new_stop: float, ctx: StepContext) -> Optional[Action]:
        """
        Build a trailing set_stop action, enforcing "only tightens": a new stop
        that would loosen the current one is ignored (returns None).

        构造移动止损动作，并强制"只进不退"：会放松现有止损的新价位被忽略（返回 None）。
        """
        p = ctx.position
        if p is None or new_stop is None:
            return None
        cur = p.stop_price
        if cur is not None and ((p.direction == "long" and new_stop <= cur) or (p.direction == "short" and new_stop >= cur)):
            return None
        return Action(kind="set_stop", rule_id=rule_id, stop_price=float(new_stop), reason="trail")

    def _set_stop(self, rule_id: str, stop_price: float) -> Action:
        """
        Build an unconditional set_stop action.

        构造无条件设置止损的动作。
        """
        return Action(kind="set_stop", rule_id=rule_id, stop_price=float(stop_price), reason="set")

    def _close(self, rule_id: str, reason: str, ctx: StepContext) -> Action:
        """
        Build the close action for an exit path.

        构造某条出场路径的平仓动作。
        """
        p = ctx.position
        return Action(kind="close", rule_id=rule_id, direction=p.direction if p else None,
                      price=ctx.last_price, size=p.size if p else None, reason=reason)
