"""
Agents: read the English part only. 中文仅供人类阅读。

Strategy driver for "大小周期共振" — generated by sf_driver.py gen at 2026-10-01T18:18:21+08:00.
Do not edit by hand; edit the `flow` section of S7_formal.json and regenerate.

This module turns the strategy's execution steps into code. `StrategyDriver.step(ctx)`
is a generated state machine: on every evaluation it walks the flow rules in order,
calls the callbacks of `StrategyCallbacks` (implemented by the downstream agent) with
the inputs they declared, and returns a list of `Action`s. The driver never places
orders: the downstream agent implements `ExecutionPort`, executes each action and keeps
`Position` up to date for the next call. Two things are built into the driver rather
than delegated: detecting that the stop was hit (exit path one, deterministic) and
sizing a new position from the account's per-trade risk fraction and the callback's
stop distance. `RecordingPort` is an in-memory reference port used by the dry-run and
by tests; it also documents how a real port is expected to update the position.

本模块把策略的执行步骤变成代码。`StrategyDriver.step(ctx)` 是生成的状态机：每次评估按顺序
走一遍 flow 规则，用各回调声明的输入调用下游实现的 `StrategyCallbacks`，返回一组 `Action`。
driver 不下单：下游实现 `ExecutionPort`，执行每个动作并为下一次调用维护 `Position`。两件事
内置在 driver 里而不交给回调：判断止损是否被打（出场路径一，确定性规则）和按账户单笔风险比例
与回调给出的止损距离反算仓位。`RecordingPort` 是内存版参考实现，供 dry-run 与测试使用，也说明
了真实下单端应如何更新持仓。
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal, Optional, Protocol

from S7_callbacks_stub import (StrategyCallbacks, Position, Instrument, MarketData, Bar, EntryDecision, StopDistance, Direction)  # noqa: F401

ActionKind = Literal["enter", "close", "set_stop"]


@dataclass
class Action:
    """
    One instruction from the driver to the execution port. `kind` is enter /
    close / set_stop; `reason` distinguishes `set_stop` at cost ("cost") from a
    trailing move ("trail") and names the exit path for `close` ("stop",
    "reversal", ...). `rule_id` is the flow rule that produced it.

    driver 发给下单端的一条指令。`kind` 为 enter / close / set_stop；`reason` 区分移损至成本
    （"cost"）与移动止损（"trail"），并给出平仓原因（"stop"、"reversal"…）。`rule_id` 是产生
    它的 flow 规则。
    """
    kind: ActionKind
    rule_id: str
    direction: Optional[Direction] = None
    price: Optional[float] = None
    size: Optional[float] = None
    stop_price: Optional[float] = None
    reason: str = ""

    def label(self) -> str:
        """
        Short label used in traces and dry-run expectations: enter,
        move_stop_to_cost, move_stop, set_stop, close:<reason>.

        用于轨迹和 dry-run 期望值的短标签：enter、move_stop_to_cost、move_stop、set_stop、
        close:<原因>。
        """
        if self.kind == "enter":
            return "enter"
        if self.kind == "close":
            return f"close:{self.reason}" if self.reason else "close"
        return {"cost": "move_stop_to_cost", "trail": "move_stop"}.get(self.reason, "set_stop")


@dataclass
class StepContext:
    """
    Everything one evaluation of the driver may look at. The downstream agent
    builds it from its own data layer before each `step()` call.

    driver 一次评估可以看到的全部信息，由下游 agent 在每次 `step()` 前从自己的数据层构造。
    """
    instrument: Instrument
    major_tf_data: MarketData
    minor_tf_data: MarketData
    position: Optional[Position] = None
    major_tf_context: Optional[MarketData] = None
    last_price: Optional[float] = None
    now: Optional[datetime] = None
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class Account:
    """
    Account-level inputs for sizing: capital and the per-trade loss fraction
    (parameter per_trade_loss_ratio). `size_from_risk` implements the "light
    position" constraint: contracts = floor(capital * ratio / (stop distance in
    price × multiplier)).

    用于仓位计算的账户信息：本金和单笔亏损占比（参数 per_trade_loss_ratio）。`size_from_risk`
    实现"轻仓"约束：手数 = floor(本金 × 比例 / (止损价差 × 合约乘数))。
    """
    capital: float
    per_trade_loss_ratio: float
    min_size: float = 1.0

    def size_from_risk(self, entry_price: float, stop: "StopDistance | float", instrument: Instrument) -> float:
        """
        Position size for a new entry given the stop distance. Returns 0 when
        the risk budget cannot afford one contract.

        根据止损距离计算新仓手数；风险预算不足一手时返回 0。
        """
        distance = stop_distance_in_price(entry_price, stop)
        if distance <= 0:
            return 0.0
        per_unit = distance * max(instrument.multiplier, 1e-12)
        size = math.floor(self.capital * self.per_trade_loss_ratio / per_unit)
        return float(size) if size >= self.min_size else 0.0


def stop_distance_in_price(entry_price: float, stop: "StopDistance | float") -> float:
    """
    Convert a StopDistance (points or percent) or a bare number of points into
    a price distance.

    把 StopDistance（点数或百分比）或裸点数转换成价格距离。
    """
    if isinstance(stop, (int, float)):
        return float(stop)
    return float(stop.value) if stop.unit == "points" else float(entry_price) * float(stop.value) / 100.0


def stop_price_from(entry_price: float, direction: Direction, stop: "StopDistance | float") -> float:
    """
    Initial stop price: below entry for a long, above for a short.

    初始止损价：多头在入场价之下，空头在入场价之上。
    """
    d = stop_distance_in_price(entry_price, stop)
    return entry_price - d if direction == "long" else entry_price + d


class ExecutionPort(Protocol):
    """
    What the downstream agent implements to execute actions. `enter` must
    return the resulting Position (with stop_price set); `set_stop` must update
    position.stop_price and set position.stop_at_cost when action.reason ==
    "cost"; `close` must flatten.

    下游 agent 实现的下单接口。`enter` 必须返回建立的 Position（含 stop_price）；`set_stop`
    必须更新 position.stop_price，且在 action.reason == "cost" 时置 stop_at_cost；`close` 必须
    平仓。
    """

    def enter(self, action: Action, ctx: StepContext) -> Position: ...
    def close(self, action: Action, ctx: StepContext) -> None: ...
    def set_stop(self, action: Action, ctx: StepContext) -> None: ...


class RecordingPort:
    """
    In-memory reference ExecutionPort: fills at the action price, keeps one
    Position, records every action. Used by the dry-run and by tests.

    内存版参考下单端：按动作价格成交、维护一个 Position、记录每个动作。供 dry-run 与测试使用。
    """

    def __init__(self) -> None:
        """
        Start flat with an empty action log.

        初始为空仓、空日志。
        """
        self.position: Optional[Position] = None
        self.log: list[Action] = []

    def apply(self, action: Action, ctx: StepContext) -> None:
        """
        Dispatch one action to enter / set_stop / close.

        把一个动作分发到 enter / set_stop / close。
        """
        self.log.append(action)
        {"enter": self.enter, "close": self.close, "set_stop": self.set_stop}[action.kind](action, ctx)

    def enter(self, action: Action, ctx: StepContext) -> Position:
        """
        Open a position at the action price with the given stop.

        按动作价格开仓并设置止损。
        """
        self.position = Position(
            instrument=ctx.instrument, direction=action.direction, entry_price=float(action.price),
            entry_time=ctx.now or datetime.now(), size=float(action.size or 0), stop_price=action.stop_price,
            stop_at_cost=False,
        )
        return self.position

    def close(self, action: Action, ctx: StepContext) -> None:
        """
        Flatten.

        平仓。
        """
        self.position = None

    def set_stop(self, action: Action, ctx: StepContext) -> None:
        """
        Move the stop; a "cost" move marks stop_at_cost.

        移动止损；原因为 "cost" 时标记 stop_at_cost。
        """
        if self.position is not None:
            self.position.stop_price = action.stop_price
            if action.reason == "cost":
                self.position.stop_at_cost = True


class StrategyDriverBase:
    """
    Runtime shared by every generated driver: state, built-in stop-hit test and
    the action constructors used by the generated `step()`.

    所有生成的 driver 共用的运行时：状态、内置的止损触发判断，以及生成的 `step()` 使用的动作
    构造器。
    """

    initial_state: str = "FLAT"

    def __init__(self, callbacks: StrategyCallbacks, account: Account) -> None:
        """
        Bind the callbacks implementation and the account; start in the
        initial state.

        绑定回调实现与账户，置为初始状态。
        """
        self.callbacks = callbacks
        self.account = account
        self.state = self.initial_state

    def stop_hit(self, ctx: StepContext) -> bool:
        """
        Exit path one: the last price has reached the position's stop (long:
        at or below; short: at or above).

        出场路径一：最新价触及持仓止损（多头：不高于止损价；空头：不低于止损价）。
        """
        p = ctx.position
        if p is None or p.stop_price is None or ctx.last_price is None:
            return False
        return ctx.last_price <= p.stop_price if p.direction == "long" else ctx.last_price >= p.stop_price

    def _enter(self, rule_id: str, direction: Direction, entry_price: float, stop: "StopDistance | float",
               ctx: StepContext) -> Action:
        """
        Build the enter action: size from account risk, initial stop from the
        stop distance.

        构造开仓动作：按账户风险反算手数，按止损距离算初始止损价。
        """
        size = self.account.size_from_risk(entry_price, stop, ctx.instrument)
        return Action(kind="enter", rule_id=rule_id, direction=direction, price=float(entry_price), size=size,
                      stop_price=stop_price_from(entry_price, direction, stop))

    def _move_stop_to_cost(self, rule_id: str, ctx: StepContext) -> Action:
        """
        Build the set_stop action that moves the stop to the entry price.

        构造把止损移到入场价的动作。
        """
        return Action(kind="set_stop", rule_id=rule_id, stop_price=float(ctx.position.entry_price), reason="cost")

    def _move_stop(self, rule_id: str, new_stop: float, ctx: StepContext) -> Optional[Action]:
        """
        Build a trailing set_stop action, enforcing "only tightens": a new stop
        that would loosen the current one is ignored (returns None).

        构造移动止损动作，并强制"只进不退"：会放松现有止损的新价位被忽略（返回 None）。
        """
        p = ctx.position
        if p is None or new_stop is None:
            return None
        cur = p.stop_price
        if cur is not None and ((p.direction == "long" and new_stop <= cur) or (p.direction == "short" and new_stop >= cur)):
            return None
        return Action(kind="set_stop", rule_id=rule_id, stop_price=float(new_stop), reason="trail")

    def _set_stop(self, rule_id: str, stop_price: float) -> Action:
        """
        Build an unconditional set_stop action.

        构造无条件设置止损的动作。
        """
        return Action(kind="set_stop", rule_id=rule_id, stop_price=float(stop_price), reason="set")

    def _close(self, rule_id: str, reason: str, ctx: StepContext) -> Action:
        """
        Build the close action for an exit path.

        构造某条出场路径的平仓动作。
        """
        p = ctx.position
        return Action(kind="close", rule_id=rule_id, direction=p.direction if p else None,
                      price=ctx.last_price, size=p.size if p else None, reason=reason)


class StrategyDriver(StrategyDriverBase):
    """
    Generated control flow. Each block below is one flow rule; the comment names
    the rule and the summary line it implements.

    生成的控制流。下面每个代码块对应一条 flow 规则；注释给出规则编号和它实现的总结行。
    """

    def step(self, ctx: StepContext) -> list[Action]:
        """
        One evaluation: walk the rules in order and return the actions to execute.

        一次评估：按顺序走一遍规则，返回要执行的动作。
        """
        actions: list[Action] = []
        state = self.state
        position = ctx.position
        stop_hit = self.stop_hit(ctx)
        direction = entry = stop = reversed = favorable = new_stop = None

        # F01 [execution_steps.1] major_timeframe_direction (大周期方向判定): 每次评估先刷新大周期方向
        direction = self.callbacks.major_timeframe_direction(major_tf_data=ctx.major_tf_data, instrument=ctx.instrument)

        # F02 [execution_steps.2] minor_timeframe_entry_signal (小周期入场信号): 只在方向明确时评估同向入场信号
        if state == 'FLAT' and (direction in ('long', 'short')):
            entry = self.callbacks.minor_timeframe_entry_signal(minor_tf_data=ctx.minor_tf_data, major_direction=direction, major_tf_context=ctx.major_tf_context)

        # F03 [execution_steps.3] initial_stop_level (小周期止损): 入场并按小周期止损设初始止损；此后只看大周期
        if state == 'FLAT' and (entry is not None and entry.decision == 'enter'):
            stop = self.callbacks.initial_stop_level(minor_tf_data=ctx.minor_tf_data, entry_price=entry.entry_price, direction=direction)
            actions.append(self._enter('F03', direction=direction, entry_price=entry.entry_price, stop=stop, ctx=ctx))
            self.state = 'IN_POSITION'
            return actions

        # F04 [exit_and_risk.4]: 出场路径一：打止损
        if state == 'IN_POSITION' and (stop_hit):
            actions.append(self._close('F04', 'stop', ctx))
            self.state = 'FLAT'
            return actions

        # F05 [execution_steps.5] major_trend_reversal (趋势反转): 出场路径二：大周期趋势反转主动清仓
        if state == 'IN_POSITION':
            reversed = self.callbacks.major_trend_reversal(major_direction=direction, major_tf_data=ctx.major_tf_data, position=ctx.position)
            if reversed:
                actions.append(self._close('F05', 'reversal', ctx))
                self.state = 'FLAT'
                return actions

        # F06 [execution_steps.4] favorable_move (有利运动): 有利运动后尽快移损至成本
        if state == 'IN_POSITION' and (not position.stop_at_cost):
            favorable = self.callbacks.favorable_move(major_tf_data=ctx.major_tf_data, position=ctx.position)
            if favorable:
                actions.append(self._move_stop_to_cost('F06', ctx))

        # F07 [execution_steps.5] major_timeframe_trailing_stop (大周期移动止损): 移损至成本后按大周期信号移动止损，只进不退
        if state == 'IN_POSITION' and (position.stop_at_cost):
            new_stop = self.callbacks.major_timeframe_trailing_stop(major_tf_data=ctx.major_tf_data, position=ctx.position)
            if new_stop is not None:
                _a = self._move_stop('F07', new_stop, ctx)
                if _a is not None:
                    actions.append(_a)

        return actions
