"""
Agents: read the English part only. 中文仅供人类阅读。

Strategy callbacks stub for "大小周期共振" — generated by sf_formal.py gen-stub at 2026-09-23T23:56:28+08:00.

This file is the contract between the strategy-formalizer output and the
downstream trading agent. Every abstract method of StrategyCallbacks is one
decision the strategy delegates to the downstream agent (a role=callback
term). The method docstring carries the agreed definition, the point in the
execution steps where it is invoked, its inputs and output, and every
auxiliary, constraint and parameter term that qualifies it. The dataclasses
above the class are the standard interface types every stub shares: bars,
market data, instrument, position, and the two compound results. Implement a
subclass and fill the dataclasses from your own data layer; do not edit this
file by hand, regenerate it from S7_formal.json instead. Market data,
instrument lists and factor helpers are the downstream agent's own concern.

本文件是 strategy-formalizer 的产出与下游交易 agent 之间的契约。StrategyCallbacks 的每个
抽象方法对应策略交给下游 agent 判断的一个决策（role=callback 的术语）。方法 docstring 包含
商定的定义、在执行步骤中的调用位置、输入输出，以及限定它的全部辅助/约束/参数术语。类之前的
dataclass 是所有桩代码共用的标准接口类型：K 线、行情数据、品种、持仓，以及两个复合结果。
请实现子类，并用你自己的数据层填充这些 dataclass；不要手工修改本文件，需要变更时从
S7_formal.json 重新生成。行情数据、品种列表、因子计算由下游 agent 自行提供。
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal, Optional

Direction = Literal["long", "short"]
"""Position / signal direction. 持仓或信号方向。"""


@dataclass
class Bar:
    """
    One OHLCV bar of any timeframe. The downstream agent fills it from its
    own data source; `extra` carries indicator values or anything else.

    任意周期的一根 OHLCV K 线。由下游 agent 从自己的数据源填充；`extra` 放指标值等附加信息。
    """
    time: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    open_interest: Optional[float] = None
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class MarketData:
    """
    Bars of one instrument on one timeframe, newest last, plus the timeframe
    label (e.g. "1d", "30m") and free-form context such as precomputed
    indicators or support/resistance levels.

    某品种在某一周期上的 K 线序列（最新在最后），加上周期标签（如 "1d"、"30m"）和自由格式的
    上下文（预计算指标、支撑阻力位等）。
    """
    instrument: str
    timeframe: str
    bars: list[Bar]
    context: dict[str, Any] = field(default_factory=dict)


@dataclass
class Instrument:
    """
    What is being traded: symbol, contract (if any), tick size, multiplier.

    交易对象：代码、合约（若有）、最小变动价位、合约乘数。
    """
    symbol: str
    contract: Optional[str] = None
    tick_size: float = 1.0
    multiplier: float = 1.0
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class Position:
    """
    An open position as the callbacks see it.

    回调所看到的当前持仓。
    """
    instrument: Instrument
    direction: Direction
    entry_price: float
    entry_time: datetime
    size: float
    stop_price: Optional[float] = None
    stop_at_cost: bool = False
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class EntryDecision:
    """
    Result of an entry-signal callback: whether to enter and, if so, at what
    limit price.

    入场信号回调的结果：是否入场，入场时的限价。
    """
    decision: Literal["enter", "no_enter"]
    entry_price: Optional[float] = None
    note: str = ""


@dataclass
class StopDistance:
    """
    Result of a stop-placement callback: a distance from the entry price,
    declared as points or percent.

    止损设置回调的结果：相对入场价的距离，须声明是点数还是百分比。
    """
    value: float
    unit: Literal["points", "percent"]


class StrategyCallbacks(ABC):
    """
    Decision callbacks the downstream trading agent must implement. Each method
    corresponds to one role=callback term; read its docstring for the agreed
    definition and the auxiliary notes that constrain the implementation.

    下游交易 agent 必须实现的决策回调。每个方法对应一个 role=callback 的术语；
    方法 docstring 里是商定的定义和约束实现的辅助说明。
    """

    @abstractmethod
    def major_timeframe_direction(self, major_tf_data: MarketData, instrument: Instrument) -> Literal['long', 'short', 'uncertain']:
        """
        [CB01 / T011] 大周期方向判定

        Definition (EN): Judge the current trend direction on the major-
        timeframe chart; return exactly one of long / short / uncertain. This is
        following, not forecasting: an ongoing up-move is 'long' (only long
        trades allowed), an ongoing down-move is 'short' (only short trades
        allowed); do not try to call where a trend starts or ends. On
        'uncertain' open no new position; existing positions keep being managed
        by the normal rules unless T021 judges that uncertainty to be a high-
        confidence reversal (then the position is closed). Inputs may be the
        major-timeframe bars (price, volume) and any technical indicator; the
        method and the re-evaluation timing are the downstream agent's choice.
        The text's 'turn signal on the higher timeframe' is the same judgement:
        a change of this output is the turn.
        Invoked in: execution_steps.1
        Input major_tf_data (MarketData): Major-timeframe bars (price, volume)
        and any indicators derived from them; the time unit is the downstream
        agent's choice (see T010, T027)
        Input instrument (Instrument): The instrument being judged
        Output (enum): long, short, uncertain Current major-timeframe direction.
        'uncertain' blocks new entries; existing positions keep being managed
        unless T021 treats it as a high-confidence reversal.
        Auxiliary T002 震荡与趋势两种状态 / range_vs_trend_states: Premise: the market
        has only two states, trending (one-directional) and non-trending
        (ranging); a slow rise inside a range is still a trend. Roughly 70% of
        the time there is no trend, so the core problem of trend following is
        surviving the ranging periods ('trend trading in one sentence: withstand
        the chop'). The strategy never classifies the current state (see T005);
        'withstanding' means surviving through cheap stops and small size, never
        holding a losing position without a stop.
        Auxiliary T010 大周期 / major_timeframe: The observation scale at which an
        instrument's overall future direction is judged over a comparatively
        large unit of time. It is not restricted to a bar chart or indicator of
        one particular timeframe; any information grounded in that time scale
        may be used. Every holding-period judgement in the strategy (major-
        timeframe direction, favourable move, trailing stop, trend reversal) is
        made at this scale. The concrete time unit is not fixed; the downstream
        agent chooses it per instrument, one to two levels above the minor
        timeframe (see T027). The text's example is the daily chart.
        Constraint T005 放弃判断行情性质 / no_regime_judgement: Core constraint: never
        classify the current market as trending or ranging, and never add a
        trend/range regime filter; treat every market as a one-directional move.
        The major-timeframe direction callback answers only 'is the current
        direction long or short', never 'is this a trend'. Losses during ranges
        are controlled by cheap stops and moving the stop to cost as soon as
        possible, not by avoiding ranges.

        定义（中文）: 在大周期图表上判断当前趋势方向，输出 多 / 空 / 不确定 三值之一。判断是跟随而非预测：处于上涨途中为“多”（只做多不做空）
        ，处于下跌途中为“空”（只做空不做多），不判断趋势何时开始、何时结束。结果为“不确定”时不开新仓；已有持仓按原规则继续管理，除非该不确定被
        T021 判定为置信度较高的反转（届时清仓）。可用输入为大周期 K 线（价格、成交量）及任何技术指标，具体方法与重新评估的时机均由下游
        agent 自行决定。原文中的“高一级周期出现转向信号”与本判定是同一件事：方向改变即视为转向。
        辅助 T002 震荡与趋势两种状态: 前提性说明：市场只有两种状态——有趋势（单边）与没趋势（震荡），震荡中的上涨本质上也是趋势；据统计约
        70% 的时间没有趋势，趋势跟踪的核心矛盾是如何活过震荡期，“趋势交易就一句话：震荡扛得住”。策略不判定当前处于哪种状态（见
        T005），“扛得住”指靠低止损成本和小仓位存活，而不是扛单不止损。
        辅助 T010 大周期: 以一个比较大的时间单位去判定一个品种未来整体走势的观察尺度。它不限定为某个时间级别的 K 线图表或指标，任何以该时间尺
        度为依据的信息都可以用。策略中所有持仓期的判断——大周期方向判定、有利运动、大周期移动止损、趋势反转——都在这个尺度上做。具体时间单位不固定，由
        下游 agent 按品种选择，须与小周期相差一到两级（见 T027）；原文举例为日线。
        约束 T005 放弃判断行情性质: 策略的核心约束：不判断当前行情是趋势还是震荡，不引入任何“趋势/震荡”状态过滤器，把所有行情都当单边来做。大
        周期方向判定只回答“当下方向是多还是空”，不回答“现在是不是趋势”；震荡期的亏损靠低止损成本和尽快移损至成本来控制，而不是靠回避震荡。
        """
        raise NotImplementedError

    @abstractmethod
    def minor_timeframe_entry_signal(self, minor_tf_data: MarketData, major_direction: Direction, major_tf_context: MarketData) -> EntryDecision:
        """
        [CB02 / T013] 小周期入场信号

        Definition (EN): Decide on the minor timeframe whether to enter now;
        return enter / no-enter, and on 'enter' also a limit entry price.
        Evaluated only while T011 gives a definite direction (long or short),
        and may only produce entries in that direction (see T022). The signal
        type is unrestricted and chosen by the downstream agent; inputs may be
        minor-timeframe bars and any indicator, the T011 direction, and other
        major-timeframe information such as support/resistance. Do not chase a
        perfect entry. After a stop-out, re-entry on the next signal is allowed
        as long as the major direction is unchanged; whether to impose a cool-
        down or a cap on attempts is the downstream agent's decision.
        Invoked in: execution_steps.2-3
        Input minor_tf_data (MarketData): Minor-timeframe bars and any
        indicators
        Input major_direction (Direction): Output of major_timeframe_direction;
        the callback is only invoked while it is long or short
        Input major_tf_context (MarketData): Optional major-timeframe
        information such as support/resistance
        Output (EntryDecision): enter, no_enter
        EntryDecision(decision='enter'|'no_enter', entry_price=<limit price when
        entering>). Signal type is unrestricted but must be in the major
        direction (T022).
        Auxiliary T001 追涨杀跌 / trend_chasing_method: Auxiliary note on the
        framework as a whole: the author chose 'chase strength / sell weakness'
        (trend following) over 'sell high / buy low' (range trading) and uses
        only that approach, accepting a low win rate with a high payoff ratio.
        It characterises how positions are managed (hold with the trend, let
        profits run, never pick tops or bottoms); it does not restrict the type
        of entry signal in T013 (D010: the entry signal form is unrestricted).
        Auxiliary T002 震荡与趋势两种状态 / range_vs_trend_states: Premise: the market
        has only two states, trending (one-directional) and non-trending
        (ranging); a slow rise inside a range is still a trend. Roughly 70% of
        the time there is no trend, so the core problem of trend following is
        surviving the ranging periods ('trend trading in one sentence: withstand
        the chop'). The strategy never classifies the current state (see T005);
        'withstanding' means surviving through cheap stops and small size, never
        holding a losing position without a stop.
        Auxiliary T012 小周期 / minor_timeframe: The observation scale, at a
        comparatively small unit of time, used only to time the entry and to
        place the initial stop; not restricted to a bar chart or indicator of
        one particular timeframe. Its sole job is entry: once the position is
        open and the initial stop is set, nothing from the minor timeframe is
        consulted again. The concrete time unit is chosen by the downstream
        agent per instrument, one to two levels below the major timeframe (see
        T027) and never as low as second-level data. The text's example is
        minute bars.
        Auxiliary T026 连续止损 / consecutive_stops: Auxiliary note: being stopped
        out repeatedly in choppy markets (the text speaks of ten or more in a
        row) is unavoidable, normal trial-and-error cost; do not try to avoid it
        with a perfect entry and never abandon the stop because of it. Small
        stops and a quick move to cost keep each loss limited; catching one big
        trend in ten attempts recovers the losses and profits. The text sets no
        maximum number of consecutive stops or pause rule; whether to add one is
        the downstream agent's decision (D013).
        Constraint T004 轻仓 / light_position: Position-size constraint: the risk
        of any single trade (distance from entry price to initial stop ×
        contracts) must not exceed a fixed fraction of capital ('never bet the
        house'). That fraction is parameter T023 per_trade_loss_ratio, whose
        value the downstream agent sets. The number of contracts is derived from
        this fraction and the initial stop distance returned by T014.
        Constraint T005 放弃判断行情性质 / no_regime_judgement: Core constraint: never
        classify the current market as trending or ranging, and never add a
        trend/range regime filter; treat every market as a one-directional move.
        The major-timeframe direction callback answers only 'is the current
        direction long or short', never 'is this a trend'. Losses during ranges
        are controlled by cheap stops and moving the stop to cost as soon as
        possible, not by avoiding ranges.
        Constraint T022 逆向信号过滤 / counter_trend_filter: Hard constraint on T013:
        execute only minor-timeframe entry signals in the direction currently
        given by T011; discard every counter-direction signal. Long signals only
        while the major direction is long, short signals only while it is short,
        no entries while it is uncertain. This is the essence of multi-timeframe
        resonance: the major timeframe filters the minor timeframe's noise.

        定义（中文）: 在小周期上判断此刻是否入场，输出 入场 / 不入场；输出“入场”时附带一个入场价位（限价）。只在 T011
        给出明确方向（多或空）时评估，且只能产生与该方向同向的入场（见 T022）。信号形式不限，由下游 agent 自定；可用输入为小周期 K
        线及任何技术指标、T011 的方向，以及大周期的其他信息（如支撑阻力）。不追求完美入场点。被止损出场后，只要大周期方向不变即可凭下一个信号再次入
        场，是否设置间隔或次数上限由下游 agent 自行决定。
        辅助 T001 追涨杀跌: 对整体框架的辅助说明：作者在“高卖低买”（震荡手法）与“追涨杀跌”（趋势跟踪手法）之间选择了后者，全程只用这一种手法
        ，接受成功率低但盈亏比高的模式。它描述的是持仓管理的性质（顺势持有、让利润奔跑、不猜顶底），并不限制 T013
        的入场信号类型（D010：入场信号形式不限）。
        辅助 T002 震荡与趋势两种状态: 前提性说明：市场只有两种状态——有趋势（单边）与没趋势（震荡），震荡中的上涨本质上也是趋势；据统计约
        70% 的时间没有趋势，趋势跟踪的核心矛盾是如何活过震荡期，“趋势交易就一句话：震荡扛得住”。策略不判定当前处于哪种状态（见
        T005），“扛得住”指靠低止损成本和小仓位存活，而不是扛单不止损。
        辅助 T012 小周期: 以较小的时间单位观察同一品种、用于寻找入场时机和设置初始止损的观察尺度；不限定为某级别的 K
        线图表或指标。其唯一任务是入场：入场并设好初始止损后即不再参考小周期的任何信息。具体时间单位由下游 agent
        按品种选择，比大周期低一到两级（见 T027）且不能低到秒级；原文举例为分钟线。
        辅助 T026 连续止损: 辅助说明：在无序震荡中被连续止损（原文举例连续 10
        次乃至十几次）是不可避免的正常试错成本，不要试图靠完美入场点回避，也不要因此放弃止损。靠止损设得小、移损至成本设得快，使单笔亏损有限；10
        次里抓住一次大趋势即可把前面的亏损赚回并盈利。原文未设最大连续止损次数或暂停规则，是否设置由下游 agent 自行决定（D013）。
        约束 T004 轻仓: 仓位约束：每笔交易的风险（入场价到初始止损价的距离 × 手数）不超过本金的一个固定比例，即“不要赌身家”。该比例是参数
        T023 单笔亏损本金比例，具体数值由下游 agent 设定。手数由该比例与 T014 给出的初始止损距离反算得到。
        约束 T005 放弃判断行情性质: 策略的核心约束：不判断当前行情是趋势还是震荡，不引入任何“趋势/震荡”状态过滤器，把所有行情都当单边来做。大
        周期方向判定只回答“当下方向是多还是空”，不回答“现在是不是趋势”；震荡期的亏损靠低止损成本和尽快移损至成本来控制，而不是靠回避震荡。
        约束 T022 逆向信号过滤: 对 T013 的硬约束：只执行与 T011 当前方向同向的小周期入场信号，逆向信号一律过滤掉——大周期为多时只执
        行做多信号，为空时只执行做空信号，为不确定时不执行任何入场。这是多周期共振的本质：用大周期过滤小周期的噪音。
        """
        raise NotImplementedError

    @abstractmethod
    def initial_stop_level(self, minor_tf_data: MarketData, entry_price: float, direction: Direction) -> StopDistance:
        """
        [CB03 / T014] 小周期止损

        Definition (EN): At entry, determine the initial stop on the minor
        timeframe; return a stop distance (points or percent) that the caller
        converts into a stop price and, with T023, into position size (see
        T004). The basis is the downstream agent's choice (minor-timeframe bars,
        indicators, volatility, anything); the only requirement is that it is
        'very close': clearly smaller than one major-timeframe bar's range, so
        each loss is small and the same capital fraction allows many attempts.
        Never place the initial stop by the major timeframe. Being stopped out
        right after entry is normal trial-and-error cost.
        Invoked in: execution_steps.3
        Input minor_tf_data (MarketData): Minor-timeframe bars, indicators,
        volatility
        Input entry_price (float): The entry price returned by
        minor_timeframe_entry_signal
        Input direction (Direction): Position direction
        Output (StopDistance):  StopDistance(value, unit='points'|'percent'):
        initial stop distance from entry; the caller converts it to a stop price
        and sizes the position with per_trade_loss_ratio (T004/T023). Must be
        'very close': clearly smaller than one major-timeframe bar's range.
        Auxiliary T008 止损成本 / stop_loss_as_cost: Philosophy note: treat the stop
        loss as the cost of doing business and trend profit as revenue; revenue
        cannot be controlled, cost can. Being stopped out right after entry is
        normal trial-and-error cost. The whole method aims to minimise that cost
        (tight minor-timeframe stop plus a quick move to cost) and to risk
        minor-timeframe stop cost for major-timeframe trend profit.
        Auxiliary T012 小周期 / minor_timeframe: The observation scale, at a
        comparatively small unit of time, used only to time the entry and to
        place the initial stop; not restricted to a bar chart or indicator of
        one particular timeframe. Its sole job is entry: once the position is
        open and the initial stop is set, nothing from the minor timeframe is
        consulted again. The concrete time unit is chosen by the downstream
        agent per instrument, one to two levels below the major timeframe (see
        T027) and never as low as second-level data. The text's example is
        minute bars.
        Auxiliary T026 连续止损 / consecutive_stops: Auxiliary note: being stopped
        out repeatedly in choppy markets (the text speaks of ten or more in a
        row) is unavoidable, normal trial-and-error cost; do not try to avoid it
        with a perfect entry and never abandon the stop because of it. Small
        stops and a quick move to cost keep each loss limited; catching one big
        trend in ten attempts recovers the losses and profits. The text sets no
        maximum number of consecutive stops or pause rule; whether to add one is
        the downstream agent's decision (D013).
        Parameter T007 正期望条件 / positive_expectancy_condition: Parameter (an
        expectation / acceptance criterion, not a runtime rule): the positive-
        expectancy condition the text states, about a 30% win rate with an
        average win at least three times the average loss (payoff ratio >= 3).
        It says the edge comes from payoff ratio, not hit rate, and is used to
        judge backtests and to calibrate the trade-off between stop tightness
        (T014) and trailing (T020): loosening stops to chase a higher win rate
        contradicts this strategy.
        Parameter T023 单笔亏损本金比例 / per_trade_loss_ratio: Parameter: the maximum
        loss of one trade as a fraction of capital, used to size the position
        from the initial stop distance (see T004). The text gives only a
        counter-example: a daily-timeframe stop can lose 5% or even 10% of
        capital per trade, which is 'too expensive', and notes that the same
        capital fraction allows many more attempts with a minor-timeframe stop.
        The value should therefore be well below 5%; the downstream agent sets
        it.

        定义（中文）: 入场时在小周期上确定初始止损，输出一个止损距离（点数或百分比），由调用方换算成止损价位并据此与 T023 反算手数（见
        T004）。依据由下游 agent 自定，可用小周期 K 线、指标、波动率等任何信息，唯一要求是“很近”：明显小于大周期一根 K
        线的波动幅度，使单笔亏损很有限、同样的本金比例能试更多次。绝不按大周期设初始止损。入场后价格马上打到该止损属于正常试错成本。
        辅助 T008 止损成本: 理念性说明：把止损理解为做生意的成本，把趋势利润理解为营收——营收控制不了，成本可以控制。入场即被打损是正常的试错成
        本；整套方法的目标是把这项成本压到最低（小周期近止损 + 尽快移损至成本），用小周期的止损成本去博大周期的趋势利润。
        辅助 T012 小周期: 以较小的时间单位观察同一品种、用于寻找入场时机和设置初始止损的观察尺度；不限定为某级别的 K
        线图表或指标。其唯一任务是入场：入场并设好初始止损后即不再参考小周期的任何信息。具体时间单位由下游 agent
        按品种选择，比大周期低一到两级（见 T027）且不能低到秒级；原文举例为分钟线。
        辅助 T026 连续止损: 辅助说明：在无序震荡中被连续止损（原文举例连续 10
        次乃至十几次）是不可避免的正常试错成本，不要试图靠完美入场点回避，也不要因此放弃止损。靠止损设得小、移损至成本设得快，使单笔亏损有限；10
        次里抓住一次大趋势即可把前面的亏损赚回并盈利。原文未设最大连续止损次数或暂停规则，是否设置由下游 agent 自行决定（D013）。
        参数 T007 正期望条件: 参数（预期/验收指标，不是运行时规则）：原文给出的正期望条件——成功率约
        30%，平均每次盈利是亏损的三倍以上（盈亏比 ≥ 3）即为正期望。它说明系统的盈利来源于盈亏比而非胜率，用于评估回测结果和校准止损松紧（T014
        ）与移动止损（T020）的取舍：追求高胜率而放宽止损违背本策略。
        参数 T023 单笔亏损本金比例: 参数：单笔交易允许的最大亏损占本金的比例，用于由初始止损距离反算手数（见
        T004）。原文只给了反例——按日线设止损一次可能亏掉本金的 5% 甚至
        10%，属于“太贵”——并说同样的本金比例下小周期止损能试更多次；因此该比例应明显小于 5%，具体数值由下游 agent 设定。
        """
        raise NotImplementedError

    @abstractmethod
    def favorable_move(self, major_tf_data: MarketData, position: Position) -> bool:
        """
        [CB06 / T024] 有利运动

        Definition (EN): While holding, judge on the major timeframe whether
        price has made 'a certain favourable move' in the position's direction;
        return yes / no. 'Yes' triggers T015, moving the stop to the cost price.
        The criterion is the downstream agent's choice (major-timeframe price,
        structure, indicators, anything) but must embody 'as soon as possible,
        yet not immediately': moving the stop right after entry does not count,
        while leaving it after price has clearly moved favourably is taking
        unnecessary risk. Evaluated only until the stop has reached cost; a
        stop-out before that is normal trial-and-error cost.
        Invoked in: execution_steps.4
        Input major_tf_data (MarketData): Major-timeframe price, structure,
        indicators (minor timeframe must not be used, T018)
        Input position (Position): Open position: direction, entry price,
        current stop, time since entry
        Output (bool): yes, no yes = a sufficient favourable move has occurred;
        the caller then moves the stop to cost price (T015/T016). Evaluated only
        while the stop is still below/above cost.
        Auxiliary T008 止损成本 / stop_loss_as_cost: Philosophy note: treat the stop
        loss as the cost of doing business and trend profit as revenue; revenue
        cannot be controlled, cost can. Being stopped out right after entry is
        normal trial-and-error cost. The whole method aims to minimise that cost
        (tight minor-timeframe stop plus a quick move to cost) and to risk
        minor-timeframe stop cost for major-timeframe trend profit.
        Auxiliary T010 大周期 / major_timeframe: The observation scale at which an
        instrument's overall future direction is judged over a comparatively
        large unit of time. It is not restricted to a bar chart or indicator of
        one particular timeframe; any information grounded in that time scale
        may be used. Every holding-period judgement in the strategy (major-
        timeframe direction, favourable move, trailing stop, trend reversal) is
        made at this scale. The concrete time unit is not fixed; the downstream
        agent chooses it per instrument, one to two levels above the minor
        timeframe (see T027). The text's example is the daily chart.
        Auxiliary T016 成本价 / cost_price: The target level for the move-to-cost:
        the entry fill price, excluding commission and slippage. Once the stop
        sits there the trade carries no price loss risk.
        Auxiliary T017 零成本头寸 / zero_cost_position: Auxiliary note: the state of
        the position after the stop has been moved to cost. The position then
        carries no price loss risk and is used to go for the major-timeframe
        trend profit; repeated stop-outs are bearable because each costs little.
        The text ignores gaps and slippage; the implementer should treat 'zero
        cost' as an approximation.
        Constraint T015 尽快移损至成本 / move_stop_to_cost_asap: Execution rule bound
        to T024: as soon as T024 returns 'yes', move the stop from the initial
        stop level to the cost price T016, and never let it fall below (long) /
        rise above (short) cost afterwards. This is the soul of the whole
        approach: only then can a zero-cost position be used to go for a big
        move. The timing judgement ('as soon as possible, but not immediately')
        itself belongs to T024.
        Constraint T018 关掉小周期 / close_minor_timeframe: Position-management
        constraint (revised in S3 D002): once the position is open and the
        initial stop is set, the entry job is done and nothing from the minor
        timeframe is consulted any more; favourable move (T024), trailing stop
        (T020) and trend reversal (T021) are all judged on the major timeframe
        only. The holding time scale must be decoupled from the entry timeframe
        so that minor-timeframe noise cannot shake the position out.

        定义（中文）: 持仓期间在大周期上判断价格是否已朝持仓方向走出“一定的有利运动”，输出 是 / 否；输出“是”即触发 T015
        把止损移到成本价。认定标准由下游 agent 自定，可用大周期的价格、结构、指标等任何信息，但必须体现“尽快，但不是立刻”：入场后立即移损不算有
        利运动，价格已明显朝有利方向运动却迟迟不移则是在冒不必要的风险。只在止损尚未移到成本价之前评估；若在此之前被初始止损打出，属正常试错成本。
        辅助 T008 止损成本: 理念性说明：把止损理解为做生意的成本，把趋势利润理解为营收——营收控制不了，成本可以控制。入场即被打损是正常的试错成
        本；整套方法的目标是把这项成本压到最低（小周期近止损 + 尽快移损至成本），用小周期的止损成本去博大周期的趋势利润。
        辅助 T010 大周期: 以一个比较大的时间单位去判定一个品种未来整体走势的观察尺度。它不限定为某个时间级别的 K 线图表或指标，任何以该时间尺
        度为依据的信息都可以用。策略中所有持仓期的判断——大周期方向判定、有利运动、大周期移动止损、趋势反转——都在这个尺度上做。具体时间单位不固定，由
        下游 agent 按品种选择，须与小周期相差一到两级（见 T027）；原文举例为日线。
        辅助 T016 成本价: 移损至成本的目标价位：开仓成交价（不含手续费与滑点）。止损移到该价位后，这笔交易在价格意义上不再有亏损风险。
        辅助 T017 零成本头寸: 辅助说明：止损移到成本价之后的持仓状态。此时头寸在价格意义上没有亏损风险，可以用它去博取大周期的趋势利润；连续多次
        被止损也扛得住，因为每次的成本足够低。原文忽略跳空与滑点，下游实现时应知晓“零成本”是近似说法。
        约束 T015 尽快移损至成本: 对 T024 的执行规则：T024 一旦输出“是”，立即把止损从初始止损位移到 T016 成本价，且此后止损不
        再低于（多头）/高于（空头）成本价。这是整套理念的灵魂——只有做到它才能用零成本头寸去博大行情。“尽快但不是立刻”的时机判断本身由 T024
        承担。
        约束 T018 关掉小周期: 持仓管理约束（S3 D002 修订）：入场并设好初始止损后，入场工作即告完成，立即停止参考小周期的任何信息；此后有
        利运动（T024）、移动止损（T020）、趋势反转（T021）全部只在大周期上判断。持仓的时间尺度必须与入场周期分离，避免被小周期的波动洗出去。
        """
        raise NotImplementedError

    @abstractmethod
    def major_timeframe_trailing_stop(self, major_tf_data: MarketData, position: Position) -> float:
        """
        [CB04 / T020] 大周期移动止损

        Definition (EN): After the stop has reached cost, decide on the major
        timeframe, from major-timeframe signals, whether and where to move the
        stop; return a new stop price or 'hold'. The stop only tightens: it may
        only rise for a long / fall for a short, never move the other way, and
        never below/above cost. The basis is the downstream agent's choice with
        major-timeframe price as the primary signal (structure, indicators,
        volatility or any other major-timeframe information may also be used);
        evaluation timing is the downstream agent's choice. Applies while the
        major trend is progressing (T019); the aim is to let profits run without
        picking tops or bottoms, until the stop is hit or the major trend
        reverses and the position is closed.
        Invoked in: execution_steps.5
        Input major_tf_data (MarketData): Major-timeframe data; price is the
        primary signal
        Input position (Position): Open position with its current stop (already
        at or beyond cost)
        Output (price):  New stop price, or None to hold. Only tightens: never
        lower for a long / higher for a short than the current stop, and never
        beyond cost in the adverse direction (T015).
        Auxiliary T010 大周期 / major_timeframe: The observation scale at which an
        instrument's overall future direction is judged over a comparatively
        large unit of time. It is not restricted to a bar chart or indicator of
        one particular timeframe; any information grounded in that time scale
        may be used. Every holding-period judgement in the strategy (major-
        timeframe direction, favourable move, trailing stop, trend reversal) is
        made at this scale. The concrete time unit is not fixed; the downstream
        agent chooses it per instrument, one to two levels above the minor
        timeframe (see T027). The text's example is the daily chart.
        Auxiliary T017 零成本头寸 / zero_cost_position: Auxiliary note: the state of
        the position after the stop has been moved to cost. The position then
        carries no price loss risk and is used to go for the major-timeframe
        trend profit; repeated stop-outs are bearable because each costs little.
        The text ignores gaps and slippage; the implementer should treat 'zero
        cost' as an approximation.
        Auxiliary T019 大周期趋势发展顺利 / major_trend_progressing: Auxiliary note: the
        precondition state for trailing the stop, i.e. the major trend keeps
        developing in the position's direction and has not reversed. The text
        does not define 'progressing'; it is not a separate judgement: as long
        as the T011 direction is unchanged and T021 has not signalled a
        reversal, the trend counts as progressing and T020 keeps trailing.
        Constraint T018 关掉小周期 / close_minor_timeframe: Position-management
        constraint (revised in S3 D002): once the position is open and the
        initial stop is set, the entry job is done and nothing from the minor
        timeframe is consulted any more; favourable move (T024), trailing stop
        (T020) and trend reversal (T021) are all judged on the major timeframe
        only. The holding time scale must be decoupled from the entry timeframe
        so that minor-timeframe noise cannot shake the position out.
        Constraint T025 除趋势反转外不主动平仓 / no_discretionary_exit: Exit constraint:
        never pick tops or bottoms, never take profit discretionarily; apart
        from the active close when T021 signals a trend reversal, do not close
        positions by hand. Exits are triggered only by the stop (initial, at-
        cost or trailed); let the market decide when to leave. Requires
        tolerating open-profit give-back, even open profit turning into a loss.
        Parameter T007 正期望条件 / positive_expectancy_condition: Parameter (an
        expectation / acceptance criterion, not a runtime rule): the positive-
        expectancy condition the text states, about a 30% win rate with an
        average win at least three times the average loss (payoff ratio >= 3).
        It says the edge comes from payoff ratio, not hit rate, and is used to
        judge backtests and to calibrate the trade-off between stop tightness
        (T014) and trailing (T020): loosening stops to chase a higher win rate
        contradicts this strategy.

        定义（中文）: 止损移到成本价之后，在大周期上按大周期的信号决定是否以及把止损移到哪里，输出 一个新的止损价位 或
        “不动”。止损只进不退：多头只能上移、空头只能下移，永不反向调整，且不低于/高于成本价。依据由下游 agent 自定，以大周期的价格为主要信号，
        也可用结构、指标、波动率等任何大周期信息；评估时机由下游自选。前提是大周期趋势发展顺利（T019）；目的是让利润自己跑，不猜顶猜底，直到打止损出
        场或大周期趋势反转清仓。
        辅助 T010 大周期: 以一个比较大的时间单位去判定一个品种未来整体走势的观察尺度。它不限定为某个时间级别的 K 线图表或指标，任何以该时间尺
        度为依据的信息都可以用。策略中所有持仓期的判断——大周期方向判定、有利运动、大周期移动止损、趋势反转——都在这个尺度上做。具体时间单位不固定，由
        下游 agent 按品种选择，须与小周期相差一到两级（见 T027）；原文举例为日线。
        辅助 T017 零成本头寸: 辅助说明：止损移到成本价之后的持仓状态。此时头寸在价格意义上没有亏损风险，可以用它去博取大周期的趋势利润；连续多次
        被止损也扛得住，因为每次的成本足够低。原文忽略跳空与滑点，下游实现时应知晓“零成本”是近似说法。
        辅助 T019 大周期趋势发展顺利:
        辅助说明：移动止损的前提状态——大周期趋势朝持仓方向继续发展、尚未反转。原文未定义“顺利”，它不是独立判断：只要 T011 方向未变且 T021
        未判定反转，即视为发展顺利，T020 据此继续移动止损。
        约束 T018 关掉小周期: 持仓管理约束（S3 D002 修订）：入场并设好初始止损后，入场工作即告完成，立即停止参考小周期的任何信息；此后有
        利运动（T024）、移动止损（T020）、趋势反转（T021）全部只在大周期上判断。持仓的时间尺度必须与入场周期分离，避免被小周期的波动洗出去。
        约束 T025 除趋势反转外不主动平仓: 出场约束：不猜顶猜底、不主观止盈；除 T021 判定趋势反转时主动清仓外，不主动平仓，出场只由止损（初
        始止损、成本价止损或移动后的止损）触发，让市场决定什么时候走。前提是能承受盈利回吐、浮盈变浮亏。
        参数 T007 正期望条件: 参数（预期/验收指标，不是运行时规则）：原文给出的正期望条件——成功率约
        30%，平均每次盈利是亏损的三倍以上（盈亏比 ≥ 3）即为正期望。它说明系统的盈利来源于盈亏比而非胜率，用于评估回测结果和校准止损松紧（T014
        ）与移动止损（T020）的取舍：追求高胜率而放宽止损违背本策略。
        """
        raise NotImplementedError

    @abstractmethod
    def major_trend_reversal(self, major_direction: Literal['long', 'short', 'uncertain'], major_tf_data: MarketData, position: Position) -> bool:
        """
        [CB05 / T021] 趋势反转

        Definition (EN): While holding, judge on the major timeframe whether the
        trend has reversed; return yes / no. 'Yes' means close the position
        actively without waiting for the stop: this is the second exit path,
        independent of the stop. Reversal means either that T011's direction has
        flipped to the opposite of the position, or that T011 returns
        'uncertain' and the downstream agent judges that uncertainty to be of
        high confidence ('high confidence' is not quantified; the downstream
        agent decides inside this callback). A low-confidence 'uncertain' from
        T011 is not a reversal; the position keeps being managed by the normal
        rules. Evaluation timing is the downstream agent's choice.
        Invoked in: execution_steps.5 / exit_and_risk.5
        Input major_direction (Literal['long', 'short', 'uncertain']): Latest
        output of major_timeframe_direction
        Input major_tf_data (MarketData): Major-timeframe data, to judge the
        confidence of an 'uncertain' reading
        Input position (Position): Open position (direction)
        Output (bool): yes, no yes = trend reversed (direction flipped against
        the position, or 'uncertain' with high confidence as judged here); the
        caller closes the position actively. Independent of the stop path.
        Auxiliary T010 大周期 / major_timeframe: The observation scale at which an
        instrument's overall future direction is judged over a comparatively
        large unit of time. It is not restricted to a bar chart or indicator of
        one particular timeframe; any information grounded in that time scale
        may be used. Every holding-period judgement in the strategy (major-
        timeframe direction, favourable move, trailing stop, trend reversal) is
        made at this scale. The concrete time unit is not fixed; the downstream
        agent chooses it per instrument, one to two levels above the minor
        timeframe (see T027). The text's example is the daily chart.
        Constraint T018 关掉小周期 / close_minor_timeframe: Position-management
        constraint (revised in S3 D002): once the position is open and the
        initial stop is set, the entry job is done and nothing from the minor
        timeframe is consulted any more; favourable move (T024), trailing stop
        (T020) and trend reversal (T021) are all judged on the major timeframe
        only. The holding time scale must be decoupled from the entry timeframe
        so that minor-timeframe noise cannot shake the position out.
        Constraint T025 除趋势反转外不主动平仓 / no_discretionary_exit: Exit constraint:
        never pick tops or bottoms, never take profit discretionarily; apart
        from the active close when T021 signals a trend reversal, do not close
        positions by hand. Exits are triggered only by the stop (initial, at-
        cost or trailed); let the market decide when to leave. Requires
        tolerating open-profit give-back, even open profit turning into a loss.

        定义（中文）: 持仓期间在大周期上判断趋势是否已反转，输出 是 /
        否；输出“是”即主动清仓，不等止损被打。这是独立于打止损的第二条出场路径。反转的含义：T011 大周期方向判定的输出翻转为与持仓相反的方向，或者
        T011 输出“不确定”且下游 agent 认为该不确定的置信度较高（“置信度较高”不量化，由下游在本回调内自行判断）。T011
        输出低置信度的“不确定”时不算反转，持仓按原规则继续管理。评估时机由下游自选。
        辅助 T010 大周期: 以一个比较大的时间单位去判定一个品种未来整体走势的观察尺度。它不限定为某个时间级别的 K 线图表或指标，任何以该时间尺
        度为依据的信息都可以用。策略中所有持仓期的判断——大周期方向判定、有利运动、大周期移动止损、趋势反转——都在这个尺度上做。具体时间单位不固定，由
        下游 agent 按品种选择，须与小周期相差一到两级（见 T027）；原文举例为日线。
        约束 T018 关掉小周期: 持仓管理约束（S3 D002 修订）：入场并设好初始止损后，入场工作即告完成，立即停止参考小周期的任何信息；此后有
        利运动（T024）、移动止损（T020）、趋势反转（T021）全部只在大周期上判断。持仓的时间尺度必须与入场周期分离，避免被小周期的波动洗出去。
        约束 T025 除趋势反转外不主动平仓: 出场约束：不猜顶猜底、不主观止盈；除 T021 判定趋势反转时主动清仓外，不主动平仓，出场只由止损（初
        始止损、成本价止损或移动后的止损）触发，让市场决定什么时候走。前提是能承受盈利回吐、浮盈变浮亏。
        """
        raise NotImplementedError


PARAMETERS: dict[str, dict[str, Any]] = {
    'positive_expectancy_condition': {'term_id': 'T007', 'default': 'win_rate≈0.30, payoff_ratio≥3', 'unit': 'ratio', 'range': 'payoff_ratio >= 3 (acceptance criterion, not a runtime input)', 'description_en': 'Parameter (an expectation / acceptance criterion, not a runtime rule): the positive-expectancy condition the text states, about a 30% win rate with an average win at least three times the average loss (payoff ratio >= 3). It says the edge comes from payoff ratio, not hit rate, and is used to judge backtests and to calibrate the trade-off between stop tightness (T014) and trailing (T020): loosening stops to chase a higher win rate contradicts this strategy.'},
    'per_trade_loss_ratio': {'term_id': 'T023', 'default': 'downstream-set', 'unit': 'fraction of capital', 'range': "well below 0.05 (the text's 5-10% example is 'too expensive')", 'description_en': "Parameter: the maximum loss of one trade as a fraction of capital, used to size the position from the initial stop distance (see T004). The text gives only a counter-example: a daily-timeframe stop can lose 5% or even 10% of capital per trade, which is 'too expensive', and notes that the same capital fraction allows many more attempts with a minor-timeframe stop. The value should therefore be well below 5%; the downstream agent sets it."},
    'timeframe_gap': {'term_id': 'T027', 'default': '1-2 levels; 1 level ≈ 4-6x time unit', 'unit': 'levels', 'range': '1..2; minor timeframe never at second level; downstream may override the 4-6x default', 'description_en': 'Constraint on the gap between major and minor timeframes: one to two levels apart, not more. By default one level means a time-unit ratio of roughly 4-6x (e.g. 5m -> 30m or 15m -> 60m is one level; 5m -> daily is about two); the downstream agent may override this default manually. Lower bound: the entry timeframe must not be absurdly small; second-level data is too noisy with too many false signals.'},
}
"""Tunable parameters (role=parameter terms). 可调参数（role=parameter 的术语）。"""
