#!/usr/bin/env python3
"""
Agents: read the English part of every docstring only. 中文段落仅供人类阅读。

sf_dialog.py — the audit trail of every question the agent asked and every
answer the user gave in the dialog stages S3 (summary) and S6 (terms).

<workspace>/<stage>_dialog.json is the source of truth; <stage>_dialog.md is
a human-friendly rendering regenerated after every write. The protocol that
makes runs resumable is: the agent calls `add` for each question BEFORE it
asks the user (status "open"), then `answer` IMMEDIATELY after the user
replies (status "answered"), then `close` once the answer has been applied to
the summary or the term file (status "closed", with a `resolution` describing
what changed). A killed session therefore always leaves the open questions on
disk, and `sf_state.py status` lists them. `from-md` parses the markdown back
into json so the user may also answer questions by editing the .md file.

    sf_dialog.py add    --stage S3 --question "..." [--affects-terms T001,T002] [--affects-sections execution_steps] [--round 2]
    sf_dialog.py add    --stage S3 --batch questions.json      # [{"question": "...", "affects_terms": [...]}, ...]
    sf_dialog.py answer --stage S3 D001 --answer "..." [--resolution "..."]
    sf_dialog.py close  --stage S3 D001 [--resolution "..."]
    sf_dialog.py to-md  --stage S3
    sf_dialog.py from-md --stage S3
    sf_dialog.py list   --stage S3 [--open]

sf_dialog.py 负责记录对话阶段 S3（策略总结）和 S6（术语定义）中 agent 提出的每个问题和
用户的每个回答。<workspace>/<stage>_dialog.json 为唯一真值，<stage>_dialog.md 是每次写入
后重新生成的人类可读版本。可恢复性的关键协议是：agent 在向用户提问之前先 `add`（状态
open），用户回答后立即 `answer`（状态 answered），把回答落实到总结或术语文件后再 `close`
（状态 closed，并用 resolution 记录改动）。因此会话中断时未回答的问题一定在磁盘上，
`sf_state.py status` 会列出它们。`from-md` 能把 markdown 解析回 json，用户也可以直接在
.md 文件里作答。
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

from sf_common import (DIALOG_STAGES, DIALOG_STATUSES, load_json, next_id, now_iso, read_text, relpath,
                       resolve_workspace, save_json, say, fail, write_text)

BANNER = ("> Agents: this markdown is a rendering of the json; the json is the source of truth. "
          "Read the English headings only. 中文仅供人类阅读；可直接在此文件中填写回答后运行 from-md 同步回 json。")


def paths(ws: Path, stage: str) -> tuple[Path, Path]:
    """
    Return (json_path, md_path) for the dialog files of a stage.

    返回某阶段对话文件的 (json 路径, md 路径)。
    """
    if stage not in DIALOG_STAGES:
        fail(f"dialog stages are {DIALOG_STAGES}, got {stage}", "对话阶段只能是 S3 或 S6")
    return ws / f"{stage}_dialog.json", ws / f"{stage}_dialog.md"


def load_dialog(ws: Path, stage: str) -> dict:
    """
    Load the dialog json for a stage, creating an empty structure if the file
    does not exist yet.

    读取某阶段的对话 json，文件尚不存在时返回空结构。
    """
    jp, _ = paths(ws, stage)
    if jp.exists():
        return load_json(jp)
    return {
        "_comment_en": "Q/A audit trail. Source of truth; the .md twin is generated by sf_dialog.py to-md.",
        "_comment_zh": "问答留痕。此文件为真值，同名 .md 由 sf_dialog.py to-md 生成。",
        "stage": stage,
        "entries": [],
    }


def save_dialog(ws: Path, stage: str, data: dict, render: bool = True) -> None:
    """
    Write the dialog json and, by default, regenerate the markdown twin so
    the two never diverge for long.

    写回对话 json，并默认重新生成 markdown 副本，避免两者长期不一致。
    """
    jp, mp = paths(ws, stage)
    save_json(jp, data)
    if render:
        write_text(mp, render_md(data))


def current_round(data: dict) -> int:
    """
    Return the highest round number used so far (0 if none).

    返回目前用到的最大轮次编号（没有则为 0）。
    """
    return max((e.get("round", 1) for e in data["entries"]), default=0)


def add_question(data: dict, question: str, affects_terms: list[str], affects_sections: list[str],
                 rnd: int | None) -> dict:
    """
    Append one open question with a fresh D### id. When no round is given the
    question joins the current round if it still has open questions, else a
    new round starts. Returns the new entry.

    追加一个状态为 open 的问题并分配新的 D### id。未指定轮次时，若当前轮仍有未回答问题则
    并入当前轮，否则开启新一轮。返回新条目。
    """
    entries = data["entries"]
    if rnd is None:
        cur = current_round(data)
        has_open = any(e["status"] == "open" and e.get("round") == cur for e in entries)
        rnd = cur if (cur and has_open) else cur + 1
    entry = {
        "id": next_id((e["id"] for e in entries), "D"),
        "stage": data["stage"],
        "round": rnd,
        "asked_at": now_iso(),
        "question_zh": question.strip(),
        "answer_zh": None,
        "answered_at": None,
        "status": "open",
        "affects": {"terms": affects_terms, "sections": affects_sections},
        "resolution": None,
    }
    entries.append(entry)
    return entry


def find(data: dict, did: str) -> dict:
    """
    Return the entry with the given id or fail.

    按 id 返回条目，找不到则报错。
    """
    for e in data["entries"]:
        if e["id"] == did:
            return e
    fail(f"no dialog entry {did}", f"对话条目 {did} 不存在")
    raise AssertionError


def render_md(data: dict) -> str:
    """
    Render the dialog json as markdown grouped by round. The format is strict
    so that parse_md can read it back: each entry is a `### Dxxx [status]`
    heading followed by bold-labelled Q / A / Affects / Resolution fields.

    把对话 json 按轮次渲染为 markdown。格式是严格的，以便 parse_md 能解析回来：每个条目是
    一个 `### Dxxx [status]` 标题，后接加粗标签的 Q / A / Affects / Resolution 字段。
    """
    stage = data["stage"]
    lines = [f"# Dialog log / 对话记录 — {stage}", "", BANNER, ""]
    open_count = sum(1 for e in data["entries"] if e["status"] == "open")
    lines.append(f"Entries: {len(data['entries'])}, open: {open_count}")
    lines.append("")
    by_round: dict[int, list[dict]] = {}
    for e in data["entries"]:
        by_round.setdefault(e.get("round", 1), []).append(e)
    for rnd in sorted(by_round):
        lines.append(f"## Round {rnd}")
        lines.append("")
        for e in by_round[rnd]:
            lines.append(f"### {e['id']} [{e['status']}]")
            lines.append("")
            lines.append(f"**Q (agent, {e.get('asked_at') or ''}):**")
            lines.append(e["question_zh"] or "")
            lines.append("")
            lines.append(f"**A (user, {e.get('answered_at') or ''}):**")
            lines.append(e["answer_zh"] or "")
            lines.append("")
            aff = e.get("affects") or {}
            lines.append(f"**Affects:** terms: {', '.join(aff.get('terms') or [])}; "
                         f"sections: {', '.join(aff.get('sections') or [])}")
            lines.append("")
            lines.append("**Resolution:**")
            lines.append(e.get("resolution") or "")
            lines.append("")
    return "\n".join(lines)


ENTRY_RE = re.compile(r"^### (D\d+) \[(\w+)\]\s*$")
ROUND_RE = re.compile(r"^## Round (\d+)\s*$")
FIELD_RE = re.compile(r"^\*\*(Q|A|Affects|Resolution)(?: \((agent|user), ([^)]*)\))?:\*\*\s*(.*)$")


def parse_md(text: str) -> list[dict]:
    """
    Parse the markdown produced by render_md (possibly edited by the user)
    back into a list of entry dicts. Only fields present in the md are
    returned; the caller merges them into the json so timestamps and ids are
    preserved. A non-empty answer on an "open" entry promotes it to
    "answered".

    把 render_md 生成（可能被用户编辑过）的 markdown 解析回条目列表。只返回 md 中存在的
    字段，由调用方合并进 json 以保留时间戳和 id。open 条目若填写了非空回答，则自动升级为
    answered。
    """
    entries: list[dict] = []
    rnd = 1
    cur: dict | None = None
    field: str | None = None
    buf: dict[str, list[str]] = {}

    def flush() -> None:
        """
        Finish the entry being parsed: join buffered field lines, derive affects and status, append to entries.

        结束当前正在解析的条目：合并缓冲的字段行、推导 affects 与状态，追加到条目列表。
        """
        if cur is None:
            return
        q = "\n".join(buf.get("Q", [])).strip()
        a = "\n".join(buf.get("A", [])).strip()
        res = "\n".join(buf.get("Resolution", [])).strip()
        aff_line = " ".join(buf.get("Affects", [])).strip()
        terms, sections = [], []
        m = re.search(r"terms:\s*([^;]*);\s*sections:\s*(.*)", aff_line)
        if m:
            terms = [t.strip() for t in m.group(1).split(",") if t.strip()]
            sections = [s.strip() for s in m.group(2).split(",") if s.strip()]
        status = cur["status"]
        if status == "open" and a:
            status = "answered"
        entries.append({"id": cur["id"], "round": cur["round"], "status": status, "question_zh": q,
                        "answer_zh": a or None, "resolution": res or None,
                        "affects": {"terms": terms, "sections": sections}})

    for line in text.splitlines():
        m = ROUND_RE.match(line)
        if m:
            rnd = int(m.group(1))
            continue
        m = ENTRY_RE.match(line)
        if m:
            flush()
            cur = {"id": m.group(1), "status": m.group(2), "round": rnd}
            buf = {}
            field = None
            continue
        if cur is None:
            continue
        m = FIELD_RE.match(line)
        if m:
            field = m.group(1)
            buf[field] = [m.group(4)] if m.group(4) else []
            continue
        if field:
            buf[field].append(line)
    flush()
    return entries


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #


def cmd_add(args: argparse.Namespace) -> None:
    """
    Add one question (--question) or many (--batch file with a JSON list of
    {question, affects_terms?, affects_sections?}) as open entries, then
    print the new ids. Run this BEFORE asking the user.

    以 open 状态添加一个问题（--question）或多个问题（--batch 指向 JSON 列表文件，元素形如
    {question, affects_terms?, affects_sections?}），并打印新 id。请在向用户提问之前运行。
    """
    ws = resolve_workspace(args.workspace)
    data = load_dialog(ws, args.stage)
    items: list[dict] = []
    if args.batch:
        items = load_json(args.batch)
    if args.question:
        items.append({"question": args.question,
                      "affects_terms": [t for t in (args.affects_terms or "").split(",") if t],
                      "affects_sections": [s for s in (args.affects_sections or "").split(",") if s]})
    if not items:
        fail("nothing to add: give --question or --batch", "缺少 --question 或 --batch")
    for it in items:
        e = add_question(data, it["question"], it.get("affects_terms") or [], it.get("affects_sections") or [],
                         args.round)
        say(f"added {e['id']} (round {e['round']})", "已添加问题")
    save_dialog(ws, args.stage, data)


def cmd_answer(args: argparse.Namespace) -> None:
    """
    Store the user's answer for an entry (status -> answered) and optionally a
    resolution. Run this IMMEDIATELY after the user replies, before applying
    the answer anywhere.

    保存用户对某问题的回答（状态 -> answered），可同时给出 resolution。请在用户回答后
    立即运行，然后再去落实这个回答。
    """
    ws = resolve_workspace(args.workspace)
    data = load_dialog(ws, args.stage)
    e = find(data, args.id)
    e["answer_zh"] = args.answer.strip()
    e["answered_at"] = now_iso()
    e["status"] = "answered"
    if args.resolution:
        e["resolution"] = args.resolution.strip()
    save_dialog(ws, args.stage, data)
    say(f"{args.id} answered", f"{args.id} 已记录回答")


def cmd_close(args: argparse.Namespace) -> None:
    """
    Mark an answered entry closed once its consequence has been written into
    the summary / term file; --resolution records what changed.

    当回答已落实到总结或术语文件后，把条目标记为 closed；--resolution 记录改动内容。
    """
    ws = resolve_workspace(args.workspace)
    data = load_dialog(ws, args.stage)
    e = find(data, args.id)
    if e["status"] == "open" and not args.force:
        fail(f"{args.id} has no answer yet; use --force to close anyway", "尚未回答，强制关闭请加 --force")
    e["status"] = "closed"
    if args.resolution:
        e["resolution"] = args.resolution.strip()
    save_dialog(ws, args.stage, data)
    say(f"{args.id} closed", f"{args.id} 已关闭")


def cmd_to_md(args: argparse.Namespace) -> None:
    """
    Regenerate <stage>_dialog.md from the json.

    根据 json 重新生成 <stage>_dialog.md。
    """
    ws = resolve_workspace(args.workspace)
    data = load_dialog(ws, args.stage)
    _, mp = paths(ws, args.stage)
    write_text(mp, render_md(data))
    say(f"wrote {relpath(mp)}", "已写出 markdown")


def cmd_from_md(args: argparse.Namespace) -> None:
    """
    Merge answers / resolutions / statuses the user typed into the .md back
    into the json (ids and timestamps are preserved; unknown ids are
    reported, not created). The md is then re-rendered.

    把用户在 .md 中填写的回答 / resolution / 状态合并回 json（保留 id 与时间戳；未知 id
    只报告不创建），然后重新渲染 md。
    """
    ws = resolve_workspace(args.workspace)
    data = load_dialog(ws, args.stage)
    _, mp = paths(ws, args.stage)
    parsed = parse_md(read_text(mp))
    by_id = {e["id"]: e for e in data["entries"]}
    changed = 0
    for p in parsed:
        e = by_id.get(p["id"])
        if e is None:
            say(f"unknown id {p['id']} in md ignored", "md 中出现未知 id，已忽略")
            continue
        if p["status"] not in DIALOG_STATUSES:
            fail(f"bad status {p['status']} on {p['id']}", "状态值非法")
        before = (e["answer_zh"], e["resolution"], e["status"], e["question_zh"])
        if p["answer_zh"] and p["answer_zh"] != e["answer_zh"]:
            e["answer_zh"] = p["answer_zh"]
            e["answered_at"] = now_iso()
        e["resolution"] = p["resolution"] if p["resolution"] else e["resolution"]
        e["question_zh"] = p["question_zh"] or e["question_zh"]
        e["status"] = p["status"]
        e["affects"] = p["affects"]
        if before != (e["answer_zh"], e["resolution"], e["status"], e["question_zh"]):
            changed += 1
    save_dialog(ws, args.stage, data)
    say(f"merged md into json; {changed} entries changed", f"已合并，{changed} 条有变化")


def cmd_list(args: argparse.Namespace) -> None:
    """
    Print entries (optionally only open ones) in one line each.

    逐行打印条目（可只看 open 的）。
    """
    ws = resolve_workspace(args.workspace)
    data = load_dialog(ws, args.stage)
    for e in data["entries"]:
        if args.open and e["status"] != "open":
            continue
        q = e["question_zh"].replace("\n", " ")
        print(f"{e['id']} r{e.get('round')} [{e['status']}] {q[:80]}")


def build_parser() -> argparse.ArgumentParser:
    """
    Build the CLI.

    构建命令行。
    """
    p = argparse.ArgumentParser(description="dialog audit trail / 对话留痕")
    p.add_argument("--workspace", "-w")
    p.add_argument("--stage", "-s", required=True, choices=DIALOG_STAGES)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("add")
    s.add_argument("--question", "-q")
    s.add_argument("--batch", help="json file with a list of {question, affects_terms, affects_sections}")
    s.add_argument("--affects-terms", help="comma separated term ids")
    s.add_argument("--affects-sections", help="comma separated summary section keys")
    s.add_argument("--round", type=int)
    s.set_defaults(func=cmd_add)

    s = sub.add_parser("answer")
    s.add_argument("id")
    s.add_argument("--answer", "-a", required=True)
    s.add_argument("--resolution", "-r")
    s.set_defaults(func=cmd_answer)

    s = sub.add_parser("close")
    s.add_argument("id")
    s.add_argument("--resolution", "-r")
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_close)

    sub.add_parser("to-md").set_defaults(func=cmd_to_md)
    sub.add_parser("from-md").set_defaults(func=cmd_from_md)
    s = sub.add_parser("list")
    s.add_argument("--open", action="store_true")
    s.set_defaults(func=cmd_list)
    return p


def main(argv: list[str] | None = None) -> None:
    """
    CLI entry point.

    命令行入口。
    """
    args = build_parser().parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
