#!/usr/bin/env python3
"""
Agents: read the English part of every docstring only. 中文段落仅供人类阅读。

sf_graph.py — draw the S7 term-relationship graph.

Reads S7_formal.json and the defined term file and writes the same graph in
two text formats plus an optional bitmap: S7_term_graph.mmd (Mermaid
flowchart, renders on GitHub and in Claude Code artifacts with no tooling),
S7_term_graph.dot (Graphviz), and S7_term_graph.pdf (rendered with `dot`
from the project-local pixi environment when --pdf is given; --png also works). Nodes are the
live terms grouped into a cluster per phase; callback terms are drawn bold,
parameters as hexagons, constraints as diamonds, auxiliary notes as plain
boxes. Edges are the typed relations from formal.json. Reading the graph
answers "which auxiliary notes and constraints does callback X depend on?"
at a glance.

    sf_graph.py render S7_formal.json --terms S6_terms_defined.json [--out-prefix S7_term_graph] [--pdf] [--png]

sf_graph.py 绘制 S7 术语关系图。读取 S7_formal.json 和已定义的术语文件，以两种文本格式
（S7_term_graph.mmd 为 Mermaid 流程图，GitHub 与 Claude Code 可直接渲染；S7_term_graph.dot
为 Graphviz）输出同一张图，加 --pdf 时用项目本地 pixi 环境中的 `dot` 渲染 S7_term_graph.pdf（--png 亦可）。
节点是存活术语，按 phase 分组为子图；回调术语加粗，参数为六边形，约束为菱形，辅助说明为
普通方框。边是 formal.json 中带类型的关系。看图即可回答"回调 X 依赖哪些辅助说明和约束"。
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

from sf_common import REPO_ROOT, TERM_PHASES, fail, load_json, relpath, resolve_workspace, say, write_text
from sf_terms import load_terms

PHASE_ZH = {"market_context": "环境/方向", "entry": "入场", "position_mgmt": "持仓管理", "exit": "出场",
            "risk": "风控", "philosophy": "理念", None: "未分类"}
EDGE_STYLE_DOT = {"supports": "dashed", "constrains": "solid", "parameterizes": "dotted", "triggers": "bold",
                  "sequence": "solid", "conflicts": "solid"}
EDGE_COLOR_DOT = {"supports": "#5b8def", "constrains": "#d9534f", "parameterizes": "#7b7b7b",
                  "triggers": "#2e8b57", "sequence": "#111111", "conflicts": "#ff00ff"}


def ws_path(ws_arg: str | None, p: str) -> Path:
    """
    Resolve a file argument against the active workspace.

    相对活动 workspace 解析文件参数。
    """
    path = Path(p)
    if path.is_absolute() or path.exists():
        return path
    return resolve_workspace(ws_arg) / p


def label(t: dict) -> str:
    """
    Node label: "T001 大周期方向判定 / judge_major_direction".

    节点标签，形如 "T001 大周期方向判定 / judge_major_direction"。
    """
    en = f" / {t['name_en']}" if t.get("name_en") else ""
    return f"{t['id']} {t['name_zh']}{en}"


def to_mermaid(terms: list[dict], relations: list[dict]) -> str:
    """
    Render a Mermaid `flowchart LR` with one subgraph per phase and edge
    labels equal to the relation type. Callback nodes use `[[ ]]` shape and
    a bold class.

    渲染 Mermaid `flowchart LR`：每个 phase 一个子图，边标签为关系类型，回调节点用 `[[ ]]`
    形状并加粗。
    """
    lines = ["%% Generated by sf_graph.py — do not edit; regenerate from S7_formal.json.",
             "%% 由 sf_graph.py 生成，请勿手改。",
             "flowchart LR",
             "  classDef callback fill:#fff2cc,stroke:#b8860b,stroke-width:2px,font-weight:bold;",
             "  classDef parameter fill:#e8f0fe,stroke:#5b8def;",
             "  classDef constraint fill:#fde8e8,stroke:#d9534f;",
             "  classDef aux fill:#f5f5f5,stroke:#999;",
             "  classDef scope fill:#e9f7ef,stroke:#2e8b57;"]
    by_phase: dict[str | None, list[dict]] = {}
    for t in terms:
        by_phase.setdefault(t.get("phase"), []).append(t)
    order = list(TERM_PHASES) + [None]
    for ph in order:
        if ph not in by_phase:
            continue
        title = f"{ph} {PHASE_ZH.get(ph, '')}" if ph else "unclassified 未分类"
        lines.append(f'  subgraph {ph or "unclassified"}["{title}"]')
        for t in by_phase[ph]:
            lab = label(t).replace('"', "'")
            role = t.get("role")
            if role == "callback":
                lines.append(f'    {t["id"]}[["{lab}"]]:::callback')
            elif role == "parameter":
                lines.append(f'    {t["id"]}{{{{"{lab}"}}}}:::parameter')
            elif role == "constraint":
                lines.append(f'    {t["id"]}{{"{lab}"}}:::constraint')
            elif role == "scope":
                lines.append(f'    {t["id"]}[/"{lab}"/]:::scope')
            else:
                lines.append(f'    {t["id"]}["{lab}"]:::aux')
        lines.append("  end")
    for r in relations:
        arrow = "-.->" if r["type"] == "supports" else ("==>" if r["type"] == "triggers" else "-->")
        lines.append(f'  {r["from"]} {arrow}|{r["type"]}| {r["to"]}')
    return "\n".join(lines)


def to_dot(terms: list[dict], relations: list[dict]) -> str:
    """
    Render a Graphviz digraph with phase clusters and role-dependent node
    shapes; edges are styled by relation type.

    渲染 Graphviz 有向图：按 phase 分簇，节点形状随 role 变化，边按关系类型着色。
    """
    lines = ["// Generated by sf_graph.py — regenerate from S7_formal.json. 由脚本生成，请勿手改。",
             "digraph strategy_terms {", "  rankdir=LR;", '  node [fontname="Helvetica", fontsize=10];',
             '  edge [fontname="Helvetica", fontsize=9];']
    by_phase: dict[str | None, list[dict]] = {}
    for t in terms:
        by_phase.setdefault(t.get("phase"), []).append(t)
    for i, ph in enumerate(list(TERM_PHASES) + [None]):
        if ph not in by_phase:
            continue
        lines.append(f"  subgraph cluster_{i} {{")
        lines.append(f'    label="{ph or "unclassified"} {PHASE_ZH.get(ph, "")}"; style=rounded; color="#bbbbbb";')
        for t in by_phase[ph]:
            lab = label(t).replace('"', "'")
            role = t.get("role")
            attrs = {"callback": 'shape=box, style="rounded,bold,filled", fillcolor="#fff2cc", penwidth=2',
                     "parameter": 'shape=hexagon, style=filled, fillcolor="#e8f0fe"',
                     "constraint": 'shape=diamond, style=filled, fillcolor="#fde8e8"',
                     "scope": 'shape=parallelogram, style=filled, fillcolor="#e9f7ef"'}.get(
                role or "", 'shape=note, style=filled, fillcolor="#f5f5f5"')
            lines.append(f'    {t["id"]} [label="{lab}", {attrs}];')
        lines.append("  }")
    for r in relations:
        lines.append(f'  {r["from"]} -> {r["to"]} [label="{r["type"]}", style={EDGE_STYLE_DOT.get(r["type"], "solid")}, '
                     f'color="{EDGE_COLOR_DOT.get(r["type"], "#333333")}"];')
    lines.append("}")
    return "\n".join(lines)


def render_bitmap(dot_path: Path, out_path: Path, fmt: str = "pdf") -> bool:
    """
    Run Graphviz `dot -T<fmt>` (pdf by default, png also supported) via
    `pixi run dot` from the repo root, falling back to a `dot` on PATH.
    Returns True on success; never raises, because the rendered file is
    optional.

    从仓库根目录用 `pixi run dot` 调用 Graphviz `dot -T<fmt>`（默认 pdf，也支持 png；找不到
    时退回 PATH 中的 dot）。成功返回 True；渲染文件是可选产物，此函数不会抛异常。
    """
    png_path = out_path
    cmds = []
    if shutil.which("pixi"):
        # conda-forge graphviz needs its plugin registry generated once; `dot -c` is idempotent and
        # writes only inside .pixi/. 首次使用需注册插件，写入 .pixi/ 内部，幂等。
        subprocess.run(["pixi", "run", "--manifest-path", str(REPO_ROOT / "pixi.toml"), "dot", "-c"],
                       cwd=REPO_ROOT, capture_output=True, text=True, timeout=120)
        cmds.append(["pixi", "run", "--manifest-path", str(REPO_ROOT / "pixi.toml"), "dot", f"-T{fmt}",
                     str(dot_path), "-o", str(png_path)])
    if shutil.which("dot"):
        cmds.append(["dot", f"-T{fmt}", str(dot_path), "-o", str(png_path)])
    for cmd in cmds:
        try:
            res = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=120)
        except Exception as exc:  # noqa: BLE001
            say(f"{cmd[0]} failed: {exc}")
            continue
        if res.returncode == 0 and png_path.exists():
            return True
        say(f"{' '.join(cmd[:3])} exited {res.returncode}: {res.stderr.strip()[:200]}")
    return False


def cmd_render(args: argparse.Namespace) -> None:
    """
    Write <prefix>.mmd, <prefix>.dot and optionally <prefix>.pdf (--pdf,
    the documented S7 output) and/or <prefix>.png (--png).

    写出 <prefix>.mmd、<prefix>.dot，可选 <prefix>.pdf（--pdf，S7 的正式产出）和/或
    <prefix>.png（--png）。
    """
    formal = load_json(ws_path(args.workspace, args.path))
    terms = load_terms(ws_path(args.workspace, args.terms))
    live = [t for t in terms["terms"] if t["status"] != "dropped"]
    known = {t["id"] for t in live}
    # Callback / parameter ids (CB01, P01) are drawn as their underlying term nodes.
    # 回调/参数 id 映射为对应术语节点。
    alias = {c["id"]: c["term_id"] for c in formal.get("callbacks", [])}
    alias.update({p_["id"]: p_["term_id"] for p_ in formal.get("parameters", [])})
    rels = [{**r, "from": alias.get(r["from"], r["from"]), "to": alias.get(r["to"], r["to"])}
            for r in formal.get("relations", [])]
    rels = [r for r in rels if r["from"] in known and r["to"] in known and r["from"] != r["to"]]
    skipped = len(formal.get("relations", [])) - len(rels)
    if skipped:
        say(f"skipped {skipped} relations whose endpoints are not live terms", "跳过端点非存活术语的关系")
    prefix = ws_path(args.workspace, args.out_prefix)
    mmd, dot = prefix.with_suffix(".mmd"), prefix.with_suffix(".dot")
    write_text(mmd, to_mermaid(live, rels))
    write_text(dot, to_dot(live, rels))
    say(f"wrote {relpath(mmd)} and {relpath(dot)} ({len(live)} nodes, {len(rels)} edges)", "已写出图文件")
    for flag, fmt in ((args.pdf, "pdf"), (args.png, "png")):
        if not flag:
            continue
        out = prefix.with_suffix(f".{fmt}")
        if render_bitmap(dot, out, fmt):
            say(f"wrote {relpath(out)}", f"已渲染 {fmt}")
        else:
            say(f"{fmt} not rendered (run `pixi install` to get graphviz); mmd/dot are still valid",
                f"{fmt} 未渲染（运行 pixi install 安装 graphviz）；mmd/dot 仍可用")


def build_parser() -> argparse.ArgumentParser:
    """
    Build the CLI.

    构建命令行。
    """
    p = argparse.ArgumentParser(description="term graph / 术语关系图")
    p.add_argument("--workspace", "-w")
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("render")
    s.add_argument("path")
    s.add_argument("--terms", required=True)
    s.add_argument("--out-prefix", default="S7_term_graph")
    s.add_argument("--pdf", action="store_true", help="also render <prefix>.pdf via graphviz (S7 output)")
    s.add_argument("--png", action="store_true", help="also render <prefix>.png")
    s.set_defaults(func=cmd_render)
    return p


def main(argv: list[str] | None = None) -> None:
    """
    CLI entry point.

    命令行入口。
    """
    args = build_parser().parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
